In [1]:
import numpy as np

In [2]:
# array that starts from the integer 1, ends at 20, incremented by 3
arr1 = np.arange(1,20,3)
arr1

array([ 1,  4,  7, 10, 13, 16, 19])

In [9]:
# Create a new array of shape 3 with random numbers between 0 and 1
arr2 = np.random.rand(3)
arr2

array([0.10636762, 0.32028409, 0.70943187])

In [16]:
# Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]]
arr2D = np.array([[10,20,45], [30,12,16], [42,17,56]])
arr2D

array([[10, 20, 45],
       [30, 12, 16],
       [42, 17, 56]])

In [17]:
# Slice the 2D array to get the first two rows
arr2Drowfirst = arr2D[:2,:]
arr2Drowfirst

array([[10, 20, 45],
       [30, 12, 16]])

In [18]:
# slice the 2D array to get the last two rows
arr2Drowlast = arr2D[1:,:]
arr2Drowlast

array([[30, 12, 16],
       [42, 17, 56]])

### Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [20]:
# create 2x2 arrays
array1 = np.array([[101,102],[103,104]])
array2 = np.array([[105,106],[107,108]])

In [23]:
# stack the elements vertically
vertical_stack = np.vstack([array1,array2])
print('Vertical stack of array is \n', vertical_stack)


Vertical stack of array is 
 [[101 102]
 [103 104]
 [105 106]
 [107 108]]


In [24]:
# stack the elements horizontally
horizontal_stack = np.hstack([array1,array2])
print('Horizontal stack of array is \n', horizontal_stack)

Horizontal stack of array is 
 [[101 102 105 106]
 [103 104 107 108]]


In [40]:
# split arrays into smaller arrays
split_vertical1 = np.vsplit(vertical_stack,2) #split vertically
print('Vertical array split vertically: \n', split_vertical1)

split_vertical2 = np.hsplit(vertical_stack,2) #split horizontally
print('\n Vertical array split horizontally: \n', split_vertical2)

split_horizontal1 = np.vsplit(horizontal_stack,2) # split vertically
print('\n Horizontal array split vertically: \n', split_horizontal1)

split_horizontal2 = np.hsplit(horizontal_stack,2) # split horizontally
print('\n Horizontal array split horizontally: \n', split_horizontal2)

Vertical array split vertically: 
 [array([[101, 102],
       [103, 104]]), array([[105, 106],
       [107, 108]])]

 Vertical array split horizontally: 
 [array([[101],
       [103],
       [105],
       [107]]), array([[102],
       [104],
       [106],
       [108]])]

 Horizontal array split vertically: 
 [array([[101, 102, 105, 106]]), array([[103, 104, 107, 108]])]

 Horizontal array split horizontally: 
 [array([[101, 102],
       [103, 104]]), array([[105, 106],
       [107, 108]])]


### Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?  Demonstrate the case when it is not possible to

In [43]:
#create metrix
X = ([[5,7,2], [4,5,6], [7,4,2]])
Y = ([[4,2], [6,2], [4,2]])

print ('With matrix multiplication it is important that the number of the columns in the first matrix should match the number of the rows in the second matrix. Hence X*Y is possible where as Y*X is not possible \n')

# Multiplication of metrix
Z = np.dot(X,Y)
print ('Multiplication is \n', Z)

With matrix multiplication it is important that the number of the columns in the first matrix should match the number of the rows in the second matrix. Hence X*Y is possible where as Y*X is not possible 

Multiplication is 
 [[70 28]
 [70 30]
 [60 26]]


### Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [50]:
# Create array
x = np.array([2,-1,-8])
y = np.array([3,1,-2])

Shape of vector x is :  (3,)
Dimention of vector x is : 1


In [51]:
# find shape of vector x
print ('Shape of vector x is : ', x.shape)

Shape of vector x is :  (3,)


In [52]:
# find dimention of vector x
print ('Dimention of vector x is :', x.ndim)

Dimention of vector x is : 1


In [56]:
# Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1)

# reshape the vector x
x_reshape = x.reshape((3,1))
print('The reshaped vector x is: \n', x_reshape)

# reshape the vector y
y_reshape = y.reshape((3,1))

# dimention of y after reshape
y_dim = y_reshape.ndim
print('\n Dimention of vector y after reshape is :', y_dim)

The reshaped vector x is: 
 [[ 2]
 [-1]
 [-8]]

 Dimention of vector y after reshape is : 2


### How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

The way NumPy handles arrays with various shapes while performing arithmetic operations is known as broadcasting. The smaller array is "broadcast" across the larger array, subject to specific limitations, ensuring that their forms match.  

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when they are equal, or one of them is 1. If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes.

In [67]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
number = 6
ar = np.array([4,1,3])

In [69]:
#subtraction of matrix
subtraction1 = matrix - number 
print('Subtraction of matrix with scalar is : \n', subtraction1)

subtraction2 = matrix - ar
print('\n Subtraction of matrix with 1D array is : \n', subtraction2)

Subtraction of matrix with scalar is : 
 [[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]

 Subtraction of matrix with 1D array is : 
 [[-3  1  0]
 [ 0  4  3]
 [ 3  7  6]]


In [72]:
#multiplication of matrix
multiplication1 = matrix * number
print('Multiplication of matrix with scalar is : \n', multiplication1)

multiplication2 = matrix * ar
print('\n Multiplication of matrix with 1D array is : \n', multiplication2)

Multiplication of matrix with scalar is : 
 [[ 6 12 18]
 [24 30 36]
 [42 48 54]]

 Multiplication of matrix with 1D array is : 
 [[ 4  2  9]
 [16  5 18]
 [28  8 27]]


### Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. 
### 2x1+3x2-4x3=6, x1-4x2=8
### 3y1-4y2+5y3=10,-y1+2y2-4y3=8

To solve the given system of linear equations using matrices, we can represent the system in matrix form:
for first equation:
|2 3 -4| = 6
|1 -4| = 8
If we analyze first equation as a matrix form, both formulas are not in same dimentions. Therefore solution is not possible in first equation.
If we consider 0 with multiplication of x3 ( 0x3 = 0) in second equation then matrix would become same in dimention and we may find the value of the x1 and x2.
|2 3 -4| = 6
|1 -4 0| = 8

for second equation:
|3 -4 5| = 10
|-1 2 -4| = 8

In [92]:
# for first equation
X = np.array([[2,3,-4], [1,-4,0]]) # coefficient matrices
c1 = np.array([6,8]) # constant matrices

if X.shape == c1.shape:
    solution = np.linalg.solve(X,c1)
    solution
else:
    print('Both matrices are not square so solution is not possible for given first equation. \nShape of coefficient matrice is ', X.shape, 'and shape of constant matrice is ', c1.shape)


Both matrices are not square so solution is not possible for given first equation. 
Shape of coefficient matrice is  (2, 3) and shape of constant matrice is  (2,)


In [93]:
# for second equation
y = np.array([[3,-4,5],[-1,2,-4]]) # coefficient matrices
c2 = np.array([10,8]) # constant matrices

if y.shape == c2.shape:
    solution = np.linalg.solve(y,c2)
    solution
else:
    print('Both matrices are not square so solution is not possible for given second equation. \nShape of coefficient matrice is ', y.shape, 'and shape of constant matrice is ', c2.shape)

Both matrices are not square so solution is not possible for given second equation. 
Shape of coefficient matrice is  (2, 3) and shape of constant matrice is  (2,)
