# Varun B Majithia
# Student ID - 8894799

# Importing the necessary packages

In [1]:
import numpy as np
import pandas as pd

## ##Q1) Create an array that starts from the integer 1, ends at 20, incremented by 3

In [2]:
# The numpy arange function is used to create an array in a specified range np.arange(start,stop,step)
array1 = np.arange(1,20,3)
print("The incremented by 3 numbers",array1)

The incremented by 3 numbers [ 1  4  7 10 13 16 19]


## Q2)Create a new array of shape 3 with random numbers between 0 and 1.

In [3]:
# Creating an array using np.random.rand() function which is used to generate random numbers in a uniform distribution
array2 = np.random.rand(3)
array2

array([0.34359619, 0.31194849, 0.15012734])

## Q3)Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows

In [4]:
# Creating a 2D array
array3 = np.array([[10,20,45],[30,12,16],[42,17,56]])
array3
# This is basically slicing operation performed below inorder to slice certain rows and columns from the data
#slicing the first two rows
first_two_rows = array3[:2,:]
#slcing the last two rows
last_two_rows = array3[1:,:]

In [5]:
print("The first two rows are ","\n",first_two_rows)

The first two rows are  
 [[10 20 45]
 [30 12 16]]


In [6]:
print("The Last two rows are","\n",last_two_rows)

The Last two rows are 
 [[30 12 16]
 [42 17 56]]


## Q4)Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
     

In [7]:
# Creating array1 
array1 = np.array([[100,101], [102,103]])
# Creating array2
array2 = np.array([[104,105], [106,107]])

In [8]:
print("The array1 is","\n",array1)

The array1 is 
 [[100 101]
 [102 103]]


In [9]:
print("the array2 is","\n",array2)

the array2 is 
 [[104 105]
 [106 107]]


In [10]:
#vertical stack
# vstack is a function that is used to vertically stack or concatenate arrays
arr_3_vstack = np.vstack((array1,array2))
print("The vertical stack is","\n",arr_3_vstack)

The vertical stack is 
 [[100 101]
 [102 103]
 [104 105]
 [106 107]]


In [11]:
#horizontal stack
# hstack is a function that is used to horizontally stack or concatenate arrays
arr_4_hstack = np.hstack((array1,array2))
print("The horizontal stack is","\n",arr_4_hstack)

The horizontal stack is 
 [[100 101 104 105]
 [102 103 106 107]]


In [12]:
#create a vertical split of the given arrays
vert_split = np.vsplit(arr_3_vstack,2)
print("Vertical splits is","\n",vert_split)

Vertical splits is 
 [array([[100, 101],
       [102, 103]]), array([[104, 105],
       [106, 107]])]


In [13]:
# create horizontal split of the given arrays
horizontal_split = np.hsplit(arr_4_hstack,4)
print("The horizontal split is","\n",horizontal_split)

The horizontal split is 
 [array([[100],
       [102]]), array([[101],
       [103]]), array([[104],
       [106]]), array([[105],
       [107]])]


# Q5.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices

 we can perform the matrix multiplication of the above given two matrices using matmul. can handle matrix multiplication for arrays of various dimensions and shapes

In [14]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])
multiply_matrices = np.matmul(X, Y)
print("The multiplied matrices are","\n",multiply_matrices)

The multiplied matrices are 
 [[70 28]
 [70 30]
 [60 26]]


## Q6 7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x

In [15]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

x_shape = x.shape
y_shape = y.shape

x_dim = x.ndim
y_dim = y.ndim

In [16]:
print("The shape of x is", x_shape)
print("The shape of y is:", y_shape)
print("Number of dimensions of x:", x_dim)
print("Number of dimensions of y:", y_dim)

The shape of x is (3,)
The shape of y is: (3,)
Number of dimensions of x: 1
Number of dimensions of y: 1


In [17]:
reshape_x = print("Reshaping x","\n",x.reshape(3,1))
reshape_y = print("Reshaping y","\n",y.reshape(3,1))

Reshaping x 
 [[ 2]
 [-1]
 [-8]]
Reshaping y 
 [[ 3]
 [ 1]
 [-2]]


## 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

Broadcasting is a concept in NumPy that enables us to performing operations between arrays of different shapes. It involves ways to handle operations involving arrays of different shapes and sizes

In [18]:
import numpy as np

# Creating a 3x3 matrix
mat1 = np.array([[121,131 ,141],
                   [151, 161, 171],
                   [181, 191, 200]])
print("Matrix 1 is","\n",mat1)

mat2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
print("matrix 2 is","\n",mat2)

Matrix 1 is 
 [[121 131 141]
 [151 161 171]
 [181 191 200]]
matrix 2 is 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


# Brief overview of the graphs

# Bar graph

Bar graphs are used to visualize the categorical features in a discrete data. The length of each bar is associated with
with the value of that particular category

# Scatter Graph

Scatter Plots/graphs are also known as relational graphs where they are used to determine the realtion between two numerical variables

# Line plot

Line plots are  particularly useful for showing trends and patterns in data.

# Pie charts

pie charts are used to divide the data into divisions where every division interprets percentage values

# Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions.

1.2x1+3x2-4x3=6,x1-4x2=8

2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [19]:
import numpy as np
A= np.array([[2,3,-4],[1,-4,0]])
B=np.array([6,8.0])
sol=np.linalg.solve(A,B)
sol

LinAlgError: Last 2 dimensions of the array must be square

 2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [20]:
array_1=np.array([[3,-4,5],[-1,2,-4]])
array_2=np.array([10,8])
output=np.linalg.solve(array_1,array_2)
output

LinAlgError: Last 2 dimensions of the array must be square

# Inference

# To solve this, there should be one or more linear equations. To find x1,x2 and x3 we need a third equation. For us to solve system of linear equations it is essential to have same number of equations as the number of variables. . Hence there is no solution