## Guru Charan Bogireddy - 8902043

### Part-A

In [7]:
import numpy as np
array1 = np.array(range(1, 20, 3))
array1

array([ 1,  4,  7, 10, 13, 16, 19])

2. Create a new array of shape 3 with random numbers between 0 and 1.

In [8]:
array2 = np.random.rand(3)
array2

array([0.68030554, 0.39195622, 0.58910511])

3. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
     
       Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.


In [9]:
# Create 2D array
array3 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# Slice the first two rows
firstTwoRows = array3[:2, :]
# Slicethe last two rows
lastTwoRows = array3[1:, :]

print(firstTwoRows)
print(lastTwoRows)

[[10 20 45]
 [30 12 16]]
[[30 12 16]
 [42 17 56]]


4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [10]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5,6],[7,8]]) 

# Stack arrays vertically
verticalStack = np.vstack((arr1, arr2))
print("vertical stack: \n", verticalStack)

#Stack arrays horizontally
horizontalStack = np.hstack((arr1, arr2))
print("horizontal stack: \n", horizontalStack)

#Split the vertical stack
verticalSplit = np.vsplit(verticalStack, 2)
print("vertical Split: \n", verticalStack)

#Split the horizontal stack
horizontalSplit = np.hsplit(horizontalStack, 2)
print("horizontal split: \n", horizontalSplit)

vertical stack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stack: 
 [[1 2 5 6]
 [3 4 7 8]]
vertical Split: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal split: 
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


5. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?   Demonstrate the case when it is not possible to.

In [11]:
X= np.matrix([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y= np.matrix([[4, 2], [6, 2], [4, 2]])
Z = np.dot(X,Y)
print("matrix multiplication: \n", Z) 

matrix multiplication: 
 [[70 28]
 [70 30]
 [60 26]]


When the number of columns in matrix A is not equal to the number of rows in matrix B, then matrix multiplication is not possible. 

In [12]:
A = np.matrix([[1, 2, 3], [4, 5, 6]])
B = np.matrix([[7, 8], [9, 10]])
C = np.dot(A,B)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

6.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. 
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [ ]:
x = np.array([2, -1, -8]) 
y = np.array([3, 1, -2])
print(f'shape of matrix X:{x.shape}, dimension:{x.ndim}')
print(f'shape of matrix Y:{y.shape}, dimension:{y.ndim}')
xReshape = x.reshape((3, 1))
yReshape  = y.reshape((3, 1))
print(f'dimensions of matrix xReshaped:{xReshape.ndim}')
print(f'dimensions of matrix yReshaped:{yReshape.ndim}')

shape of matrix X:(3,), dimension:1
shape of matrix Y:(3,), dimension:1
dimensions of matrix xReshaped:2
dimensions of matrix yReshaped:2


7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

Broadcasting does element-wise operations.

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#Declare a scalar value to perform subtraction and multiplication
scalar = 3

In [ ]:
#Subtraction using broadcasting
subtraction_result = matrix - scalar
print(subtraction_result)

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [ ]:
#Multiplication using broadcasting
multiplication_result = matrix * scalar
print(multiplication_result)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


### Part-B

1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. 
2x1 + 3x2 - 4x3 = 6
x1 - 4x2 = 8
3y1 - 4y2 + 5y3 = 10
-y1 + 2y2 - 4y3 = 8


In [ ]:
#2x1 + 3x2 - 4x3 = 6
#x1 - 4x2 = 8
#3y1 - 4y2 + 5y3 = 10
#-y1 + 2y2 - 4y3 = 8

In [ ]:
a1 = np.array([[2,3,-4],[1,-4,0]])
b1 = np.array([6,8])
print("The shape of a1 matrix is: \n", a1.shape)
print("The shape of b1 matrix is: \n", b1.shape)
#Solving x 
x = np.linalg.solve(a1,b1)

LinAlgError: Last 2 dimensions of the array must be square

The shape of matrix A is 2x3 which is a non-square matrix, we cannt calculate the determinant. Hence we cannt inverse the matrix.
To find the solution matrix [x1, x2, x3], we need to find the inverse of A multiply with matrix B. Hence it is not possible.


In [ ]:
a2 = np.array([[3,-4,5],[-1,2,-3]])
b2 = np.array([10, 8])
print("The shape of b2 matrix is: \n", b2.shape)
print("The shape of a2 matrix is: \n", a2.shape)
x2 = np.linalg.solve(a2, b2)

LinAlgError: Last 2 dimensions of the array must be square

Same with the shape of 2nd equation the matrix A is 2x3 which is a non-square matrix, we cannt calculate the determinant. Hence we cannt inverse the matrix.
To find the solution matrix [x1, x2, x3], we need to find the inverse of A multiply with matrix B. Hence it is not possible.
