# Jia Zeng 8936740 - Lab 1
---
# Part A

1. Create a Notebook to demonstrate NumPy Operations.

In [117]:
import numpy as np

---
2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [118]:
a = np.arange(1, 21, 3) # 21 is exlusive
print(a)

[ 1  4  7 10 13 16 19]


---
3. Create a new array of shape 3 with random numbers between 0 and 1.

In [119]:
np.random.seed(0)
b = np.random.rand(3)
print(b)

[0.5488135  0.71518937 0.60276338]


---
4. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
         
           Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [120]:
c = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

print("Orign data:")
print(f'{c}\n')

# slice to first two rows
print("Slice to first two rows")
print(f'{c[:2, :]}\n')

# slice to last two rows
print("Slice to last two rows")
print(c[1:, :])

Orign data:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

Slice to first two rows
[[10 20 45]
 [30 12 16]]

Slice to last two rows
[[30 12 16]
 [42 17 56]]


---
5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [121]:
e = np.arange(4).reshape(2, 2)
f = np.arange(4, 8).reshape(2, 2)

print("Stack in vertically:")
print(f'{np.vstack((e, f))}\n')

print("Stack in horizontally:")
print(f'{np.hstack((e, f))}\n')

print("Split in smaller array:")
print(f'{np.vsplit(e, 2)[0]}')
print(f'{np.vsplit(e, 2)[1]}\n')
print(f'{np.hsplit(f, 2)[0]}')
print(f'{np.hsplit(f, 2)[1]}')

Stack in vertically:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

Stack in horizontally:
[[0 1 4 5]
 [2 3 6 7]]

Split in smaller array:
[[0 1]]
[[2 3]]

[[4]
 [6]]
[[5]
 [7]]


---
 6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 

In [122]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) 
Y = np.array([[4, 2], [6, 2], [4, 2]])

np.matmul(X, Y)   

array([[70, 28],
       [70, 30],
       [60, 26]])

Demonstrate the case when it is not possible to:

In [123]:
np.matmul(Y, X)  

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

The left column numbers should be same with right row numbers.

---
7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x:

In [ ]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print(f'Shape of x: {x.shape}')
print(f'Number of dimensions of x: {x.ndim}')

Shape of x: (3,)
Number of dimensions of x: 1


Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [ ]:
print(f'Number of dimensions of x after reshape: {x.reshape(3, 1).ndim}')

Number of dimensions of x after reshape: 2


---
8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [ ]:
g = np.arange(9).reshape(3,3)

print(f'{g - 4}\n')
print(f'{g * 2}')

[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


---
# Part B
1. Solve the following two system of linear equations using matrices (find the values of x1 and x2) and 
          determine the number of solutions using the functions. 
	         
			 1. 2x1+3x2-4x3=6,x1-4x2=8

In [ ]:
x1 = np.array([[2, 3, -4], [1, -4, 0]])
y1 = np.array([6, 8])

z1 = np.linalg.solve(x1, y1)

print(z1)

LinAlgError: Last 2 dimensions of the array must be square

	         2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [ ]:
x2 = np.array([[3, -4, 5], [-1, 2, -4]])
y2 = np.array([10, 8])

z2 = np.linalg.solve(x2, y2)

print(z2)

LinAlgError: Last 2 dimensions of the array must be square

We need make the number of rows equal to the number of the column, which is n*n.

---
2. Publish the notebook as an HTML using GitHub Pages
	  In the PR description (created above) - add the direct link to the HTML.



##### Magic code for Convert to HTML
jupyter nbconvert --to html ./students-submissions/8936740/Lab1.ipynb --output-dir ./students-submissions/8936740 --TagRemovePreprocessor.enabled=True --TagRemovePreprocessor.remove_input_tags="['noshow']"