# Lab 1 - Basic Numpy Operations
<i>Tenzin Yangzom - 8896839

# PART A

In [1]:
# importing numpy package
import numpy as np

<b> 2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
# Using arange to create an array
arr1 = np.arange(1,21,3)  # 1-21 because it excludes the stop value i.e. 21
arr1

array([ 1,  4,  7, 10, 13, 16, 19])

<b> 3. Create a new array of shape 3 with random numbers between 0 and 1.

In [3]:
arr2 = np.random.rand(3)
arr2

array([0.30929973, 0.0139579 , 0.93713878])

 <b> 4. Create a 2D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

       Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [4]:
arr2d = np.array([[10,20,45], [30,12,16], [42,17,56]])
arr2d

array([[10, 20, 45],
       [30, 12, 16],
       [42, 17, 56]])

In [5]:
# Slice 2d array to get first 2 rows
sliced_arr2d = arr2d[:2, :]
sliced_arr2d

array([[10, 20, 45],
       [30, 12, 16]])

In [6]:
# Slice 2d array to get last 2 rows
sliced_arr2d = arr2d[-2:, :]
sliced_arr2d

array([[30, 12, 16],
       [42, 17, 56]])

<b>  5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [7]:
# create 2X2 array
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [8]:
a

array([[1, 2],
       [3, 4]])

In [9]:
b

array([[5, 6],
       [7, 8]])

In [10]:
# stack it vertically
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
# stack it horizontally
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [12]:
# split into smaller arrays
np.hsplit(a, 2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [13]:
np.vsplit(b, 2)

[array([[5, 6]]), array([[7, 8]])]

<b> 6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? <br> Demonstrate the case when it is not possible to.

<b> <i>Multiplication is possible since the number of the columns in the first matrix matches the number of rows in the second matrix.

In [14]:
X = np.array([[5, 7, 2],
              [4, 5, 6],
              [7, 4, 2]])

Y = np.array([[4, 2],
              [6, 2],
              [4, 2]])

In [15]:
np.matmul(X,Y)

array([[70, 28],
       [70, 30],
       [60, 26]])

<i> Demonstrating when it is not possible

In [16]:
X = np.array([[5, 7, 2],
              [4, 5, 6]])

Y = np.array([[4, 2],
              [6, 2]])

In [17]:
np.matmul(X,Y)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

<b> 7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. <br> Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [ ]:
x = np.array([2,-1,-8])
y = np.array([3,1,-2])

# Shape of of x
x.shape

(3,)

In [ ]:
# Numnber of dimension
x.ndim

1

In [ ]:
# Reshaping vector x to matrix of size (3,1)
x.reshape(3,1)

array([[ 2],
       [-1],
       [-8]])

In [ ]:
x.reshape(3,1).shape

(3, 1)

In [ ]:
# Checking number of dimensions after reshaping x to a matrix of (3,1)
x.reshape(3,1).ndim

2

In [ ]:
# Checking number of dimensions after reshaping y to a matrix of (3,1)
y.reshape(3,1)

array([[ 3],
       [ 1],
       [-2]])

In [ ]:
y.reshape(3,1).ndim

2

<b> 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

<b><i> Broadcasting in array, operations are performed on element by element. For example, multiplication and subtraction are done element by element on the array of different shape.

In [ ]:
# Broadcasting subtraction
x = np.arange(9).reshape(3,3)  # 3X3 matrix
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x - 2 # subtracts each element

array([[-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
# Broadcasting multiplication
x * 2  # multiplies each element

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
np.dot(x,2)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

# PART B

<b>1. Solve the following two system of linear equations using matrices (find the values of x1 and x2) and
      determine the number of solutions using the functions. <br> <br> 1. 2x1+3x2-4x3=6,  x1-4x2=8 <br> <br> 2. 3y1-4y2+5y3=10, -y1+2y2-4y3=8

## 1

In [ ]:
# System of equation in matrix form : AX = B
A = np.array([[2,3,-4],[1,-4,0]]) # coefficient

B = np.array([6,8]) # constants

print("Shape of A matrix is: \n", A.shape)
print("Shape of B matrix is: \n", B.shape)



Shape of A matrix is: 
 (2, 3)
Shape of B matrix is: 
 (2,)


<i> To find x1 and x2, we can use X = A(inverse)*B. But the shape of matrix is 2X3 so inverse operation won't work.

<i >The above system of linear equation lack a sufficient number of equation and additional informations to determine the unique solution. <br>
Therfore, It is not possible to find unique solution for the given systems of equations.

In [ ]:
# Error
np.linalg.solve(A, B)

LinAlgError: ignored

## 2

In [ ]:
# System of equation in matrix form : AX = B
A = np.array([[3, -4, 5],[-1, 2, -4]]) # coefficient

B = np.array([10 ,8]) # constants

print("Shape of A matrix is: \n", A.shape)
print("Shape of B matrix is: \n", B.shape)



Shape of A matrix is: 
 (2, 3)
Shape of B matrix is: 
 (2,)


<i> To find y1 and y2 and y3 we can use X = A(inverse)*B. But the shape of matrix is 2X3 so inverse operation won't work.

<i >The above system of linear equation lack a sufficient number of equation and additional informations to determine the unique solution. <br>
Therfore, It is not possible to find unique solution for the given systems of equations.
