# Practical Lab 1
# Waseem Raja Shaik
# 8894805

1.Create a Notebook to demonstrate NumPy Operations.

In [16]:
import numpy as np
import plotly.express as px

2.Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [3]:
arr_1 = np.arange(1,20,3)
arr_1

array([ 1,  4,  7, 10, 13, 16, 19])

3.Create a new array of shape 3 with random numbers between 0 and 1.

In [4]:
arr_2 = np.random.rand(1,3)
print('arr_2:',arr_2)
arr_3 = np.random.rand(3,3)
print('arr_3:',arr_3)

arr_2: [[0.40329151 0.79158884 0.58843237]]
arr_3: [[0.9232733  0.9152338  0.87104205]
 [0.90580419 0.2913051  0.43298241]
 [0.50080301 0.99743162 0.23325001]]


4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 

Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.


In [5]:
arr_5 = np.array([[10,20,45], [30,12,16], [42,17,56]])
print(arr_5[0:2])
print(arr_5[len(arr_5):0:-1])

[[10 20 45]
 [30 12 16]]
[[42 17 56]
 [30 12 16]]


5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [80]:
arr_6_1 = [[1,2],[3,4]]
arr_6_2 = [[5,6],[7,8]]
print(arr_6_1)
print(arr_6_2)
# vertically
ver_stack = np.vstack((arr_6_1,arr_6_2))
print(ver_stack)
# vertical split
print(np.vsplit(ver_stack,2))
# horizontally
hor_stack = np.hstack((arr_6_1, arr_6_2))
print(hor_stack)
# horizontal split
print(np.hsplit(hor_stack,2))
# split the array into smaller arrays
combined_array = np.concatenate((arr_6_1,arr_6_2),axis=None)
print(np.split(combined_array,combined_array.size))

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[[1 2 5 6]
 [3 4 7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8])]


6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 


In [7]:
X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y= ([[4, 2], [6, 2], [4, 2]])
# Demonstrate the case when it is not possible to.
# np.multiply(X,Y) it's not possible due to elements not being of same wise
np.matmul(X,Y)

array([[70, 28],
       [70, 30],
       [60, 26]])

7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.         
    Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1)

In [8]:
x = ([2, -1, -8])
y = ([3, 1, -2])
x_np = np.array(x)
y_np = np.array(y)
#shape
print('shape of x and y')
print('x:', x_np.shape)
print('y:', y_np.shape)
# Number of dimensions
print('number of dimensions of x and y')
print('x:', x_np.ndim)
print('y:', y_np.ndim)
# reshape of x to (3,1)
print('reshape of x to (3,1)')
print('x:', x_np.reshape((3,1)))
# reshape of y to (3,1) and get dimensions
print('reshape of y to (3,1) and finding dimensions')
print('y:', y_np.reshape((3,1)).ndim)

shape of x and y
x: (3,)
y: (3,)
number of dimensions of x and y
x: 1
y: 1
reshape of x to (3,1)
x: [[ 2]
 [-1]
 [-8]]
reshape of x to (3,1) and finding dimensions
y: 2


8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.
boardcasting in numpy means how it treats the matrix differently during arithmetic operations

In [9]:
arr_7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_8 = np.array([[10,11,12],[13,14,15],[16,17,18]])
arr_9 = np.array([[10,11,12]])
arr_10 = np.array([[10,11,12, 14]])
print(arr_7)
print(arr_8)
# subtraction
print('-------')
print('subtraction will done by row wise by elements like 10 - 1, 11 - 2, 12 - 3, 13 - 4 ... so on')
print('-------')
print(arr_8 - arr_7)
print('-------')
print('if X = 3 * 3 and Y = 3 * 1 subtraction is done then it will subtract from Y single row with X all rows.')
print('-------')
print(arr_9 - arr_7)
print('-------')
print("it's impossible to subtract if row size is not same for X and Y")
print("print(arr_10 - arr_7) error for this: operands could not be broadcast together with shapes (1,4) (3,3)")

# multiplication
print('-------')
print("Multiplication will done by row wise by elements like 10 * 1, 11 * 2, 12 * 3, 13 * 4 ... so on")
print('-------')
print(arr_8 * arr_7)
print('-------')
print("if X = 3 X 3 and Y = 3 * 1 subtraction is done then it will subtract from Y single row with X all rows.")
print('-------')
print(arr_9 * arr_7)
print('-------')
print("it's impossible to multiple if row size is not same for X and Y")
print("print(arr_7 * arr_10) error for this: operands could not be broadcast together with shapes (3,3) (1,4)")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
-------
subtraction will done by row wise by elements like 10 - 1, 11 - 2, 12 - 3, 13 - 4 ... so on
-------
[[9 9 9]
 [9 9 9]
 [9 9 9]]
-------
if X = 3 X 3 and Y = 3 * 1 subtraction is done then it will subtract from Y single row with X all rows.
-------
[[9 9 9]
 [6 6 6]
 [3 3 3]]
-------
it's impossible to subtract if row size is not same for X and Y
print(arr_10 - arr_7) error for this: operands could not be broadcast together with shapes (1,4) (3,3)
-------
Multiplication will done by row wise by elements like 10 * 1, 11 * 2, 12 * 3, 13 * 4 ... so on
-------
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
-------
if X = 3 X 3 and Y = 3 * 1 subtraction is done then it will subtract from Y single row with X all rows.
-------
[[ 10  22  36]
 [ 40  55  72]
 [ 70  88 108]]
-------
it's impossible to multiple if row size is not same for X and Y
print(arr_7 * arr_10) error for this: operands could not be broadcast together wi

9. Add Markdown text, with a headline, that provides a very brief overview of the graphs (e.g., one sentence for each). 

Feel free to add additional Markdown elements (description/additional comments)

# Brief Overview of the graphs

## Bar graph
*A graph representing categorical data with rectangular bars of varying heights.*

In [10]:
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig.show()

## Scatter graph
**A graph displaying individual data points as markers on a coordinate grid.**


In [12]:
data = px.data.iris()
fig = px.scatter(data, x="sepal_width", y="sepal_length", color="species")
fig.show()

#

## Line Plot
> A graph showing the trend of a variable over a continuous range of values.

In [13]:
df = px.data.gapminder().query("continent=='Oceania'")
fig = px.line(df, x="year", y="lifeExp", color="country", title='Life Expectancy in Oceania')fig.show()

## Pie Chart
~~A circular chart divided into sectors, representing the proportion of different categories in a dataset.~~


In [14]:
df = px.data.tips()
fig = px.pie(df, values='tip', names='day')
fig.show()


*1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions.* 
1. 2x1+3x2-4x3=6,x1-4x2=8
2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

First values are
1. 2x<sub>1</sub>+3x<sub>2</sub>-4x<sub>3</sub>=6
2. x<sub>1</sub>-4x<sub>2</sub>=8

The X matrix will be
<table>
<thead>
<th>X<sub>1</sub></th>
<th>X<sub>2</sub></th>
</thead>
<tbody>
<tr>
<td>2</td>
<td>3</td>
</tr>
<tr>
<td>1</td>
<td>-4</td>
</tr>
</tbody>
</table>


The Y matrix will be
<table>
<thead>
<th>Y</th>
</thead>
<tbody>
<tr><td>6</td></tr>
<tr><td>8</td></tr>
</tbody>
</table>


In [57]:
X = np.array([[2, 3], [1, -4]])
Y = np.array([6,8])
print('The Solution is', np.linalg.solve(X,Y))

The Solution is [ 4.36363636 -0.90909091]


2. 3y1-4y2+5y3=10,
-y1+2y2-4y3=8

Second values are
1. 3y<sub>1</sub>-4y<sub>2</sub>+5y<sub>3</sub>=10
2. -y<sub>1</sub>+2y<sub>2</sub>-4y<sub>3</sub>=8

The X matrix will be
<table>
<thead>
<th>X<sub>1</sub></th>
<th>X<sub>2</sub></th>
</thead>
<tbody>
<tr>
<td>3</td>
<td>-4</td>
</tr>
<tr>
<td>-1</td>
<td>2</td>
</tr>
</tbody>
</table>


The Y matrix will be
<table>
<thead>
<th>Y</th>
</thead>
<tbody>
<tr><td>10</td></tr>
<tr><td>8</td></tr>
</tbody>
</table>

The markdown table is not visible when convert to html
| Y |
| ---- | 
| 10 |
| 8 |

In [58]:
X = np.array([[3, -4], [-1, 2]])
Y = np.array([10,8])
print('The Solution is',np.linalg.solve(X,Y))

The Solution is [26. 17.]
