In [1]:
import numpy as np

**Creating a Array starting from 1, ending at 20, Increment by 3**

In [2]:
arr1 = np.arange(1, 21, 3)
print("Array 1:", arr1)

Array 1: [ 1  4  7 10 13 16 19]


**Create a new array of shape 3 with random numbers between 0 and 1**

In [3]:
arr2 = np.random.rand(3)
print("Array 2:", arr2)

Array 2: [0.11778592 0.28730826 0.83972439]


**Create a 2D array and perform slicing**

In [4]:
arr3 = np.array([[15, 25, 30],[25, 50, 32],[55, 89, 63]])
print("2D Array:")
print(arr3)

2D Array:
[[15 25 30]
 [25 50 32]
 [55 89 63]]


**Slice the 2D array to get the first two rows**

In [5]:
firstTwoRows = arr3[:2]
print("First Two Rows of a 2D Array:")
print(firstTwoRows)

First Two Rows of a 2D Array:
[[15 25 30]
 [25 50 32]]


**Slice the 2D array to get the last two rows**

In [6]:
lastTwoRows = arr3[1:]
print("Last two rows of a 2D Array:")
print(lastTwoRows)

Last two rows of a 2D Array:
[[25 50 32]
 [55 89 63]]


**Create two 2x2 arrays and demonstrate stacking and splitting**

In [7]:
arr4 = np.array([[1,2],[5,9]])
arr5 = np.array([[7,6],[8, 0]])

#Stack Vertically
vertical = np.vstack((arr4, arr5))
print("Stacked Vertically")
print(vertical)

#Stack Horizontally
horizontal = np.hstack((arr4, arr5))
print("Stacked Horizontally")
print(horizontal)

#Split Vertically
splitv= np.vsplit(vertical, 2)
print("Split Vertically")
print(splitv)

#Split Horizontally
splith= np.hsplit(horizontal, 2)
print("Split Horizontally")
print(splith)



Stacked Vertically
[[1 2]
 [5 9]
 [7 6]
 [8 0]]
Stacked Horizontally
[[1 2 7 6]
 [5 9 8 0]]
Split Vertically
[array([[1, 2],
       [5, 9]]), array([[7, 6],
       [8, 0]])]
Split Horizontally
[array([[1, 2],
       [5, 9]]), array([[7, 6],
       [8, 0]])]


**Matrix multiplication**

In [8]:
X= np.array([[4, 8, 9],[8, 2, 6],[7, 6, 4]])
Y = np.array([[1, 2],[7, 6],[3, 5]])

multiply = np.dot(X, Y)
print("Matrix Multiplicatiion result:")
print(multiply)

Matrix Multiplicatiion result:
[[ 87 101]
 [ 40  58]
 [ 61  70]]


**SShape and Dimensions of arrays**

In [9]:
X1 = np.array([7, -6, -4])
Y1 = np.array([5, 2, -3])

print("Shape of X1:", X1.shape)
print("Number of dimensions of X1:", X1.ndim)
 
#Reshape X1 and Y1
reshaped_X1 = X1.reshape((3,1))
reshaped_Y1 = Y1.reshape((3,1))
print(reshaped_X1)
print(reshaped_Y1)
print("Dimensions after reshaping X1:", reshaped_X1.ndim)

print("Dimensions after reshaping Y1:", reshaped_Y1.ndim)

Shape of X1: (3,)
Number of dimensions of X1: 1
[[ 7]
 [-6]
 [-4]]
[[ 5]
 [ 2]
 [-3]]
Dimensions after reshaping X1: 2
Dimensions after reshaping Y1: 2


**Broadcasting in Numpy**

In [10]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 2, 3])

subtracted = matrix - vector
print("Subtracted matrix:")
print(subtracted)

multiplied = matrix * vector
print("Multiplied matrix:")
print(multiplied)

Subtracted matrix:
[[0 0 0]
 [3 3 3]
 [6 6 6]]
Multiplied matrix:
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


**Solving the system of linear equations using matrices:**

In [11]:
# coefficient matrix A
A = np.array([[1.2, 3, -4], [1, -4, 0]])

# constant matrix B
B = np.array([[6], [8]])


X, residuals, rank, singular_values = np.linalg.lstsq(A, B, rcond=None)

# Print the values of x1 and x2
print("x1 =", X[0][0])
print("x2 =", X[1][0])


x1 = 1.5094339622641508
x2 = -1.6226415094339621


In [12]:
# Coefficient matrix A
A = np.array([[3, -4, 5], [-1, 2, -4]])

# Constant matrix B
B = np.array([[10], [8]])


Y, residuals, rank, singular_values = np.linalg.lstsq(A, B, rcond=None)

# Print the values of y1, y2, and y3
print("y1 =", Y[0][0])
print("y2 =", Y[1][0])
print("y3 =", Y[2][0])


y1 = 7.460674157303374
y2 = -4.629213483146074
y3 = -6.179775280898881
