## Lab Submission 1
## Zohair Mubasheer Ahmed - 8897082
### Part A


In [3]:
import numpy as np

- Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [4]:
array = np.arange(1, 20, 3)
array

array([ 1,  4,  7, 10, 13, 16, 19])

- Create a new array of shape 3 with random numbers between 0 and 1.

In [5]:
array = np.random.rand(3)
array

array([0.59930737, 0.08950606, 0.82825281])

- Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:  
    - Slice the 2D array to get the first two rows.


In [6]:
array = np.array([[10,20,45], [30,12,16], [42,17,56]])
array[:2]

array([[10, 20, 45],
       [30, 12, 16]])

- Slice the 2D array to get the last two rows.

In [7]:
array[-2:]

array([[30, 12, 16],
       [42, 17, 56]])

- Create two 2x2 arrays and demonstrate how you can:
    - Stack the elements 
        - 1 - Vertically
        - 2 - Horizontally


In [9]:
a = np.array([[5,6],[7,8]])
b = np.array([[1,2],[3,4]])
np.stack((a, b), axis=0)

array([[[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]]])

- Split the arrays into smaller arrays.

In [10]:
np.stack((a, b), axis=1)

array([[[5, 6],
        [1, 2]],

       [[7, 8],
        [3, 4]]])

- Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]])
    - Is it possible to multiply these matrices?


In [12]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

In [13]:
np.dot(X,Y)

array([[70, 28],
       [70, 30],
       [60, 26]])

- Demonstrate the case when it is not possible to.

In [27]:
Z = np.reshape(Y,[2, 3])
np.dot(X,Z)

ValueError: cannot reshape array of size 3 into shape (2,3)

- Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2])
    - For vector X find:
        - Shape



In [26]:
X = np.array([2, -1, -8])
Y = np.array([3, 1, -2])
X.shape

(3,)

- Number of dimensions 


In [98]:
X.ndim

1

- Reshape the vector x to a matrix of size (3,1) 


In [99]:
X = np.reshape(X,[3,1])
Y = np.reshape(Y,[3,1])
Y.shape

(3, 1)

- Determine the number of dimensions after reshaping y to a matrix of (3,1).

In [100]:
Y.ndim

2

How does broadcasting work? 
- Demonstrate the following on a 3 x 3 matrix:
    - Subtraction

In [17]:
matrix = np.array([[5,6,7],[7,8,9],[2,6,3]])
matrix

array([[5, 6, 7],
       [7, 8, 9],
       [2, 6, 3]])

In [18]:
matrix - 1

array([[4, 5, 6],
       [6, 7, 8],
       [1, 5, 2]])

- Multiplication

In [19]:
matrix * 2

array([[10, 12, 14],
       [14, 16, 18],
       [ 4, 12,  6]])

## Part B

- Solve the following two system of linear equations using matrices 
    - Find the values for the variables
    - Determine the number of solutions


- System 1 

In [25]:
s1_e1 = np.array([[2,3,-4],[1,-4,0]])
s1_e2 = np.array([6,8])
s1 = np.linalg.solve(s1_e1, s1_e2)

LinAlgError: Last 2 dimensions of the array must be square

- System 2

In [23]:
s2_e1 = np.array([[3,-4,5],[-1,2,-4]])
s2_e2 = np.array([10,8])
s2 = np.linalg.solve(s2_e1, s1_e2)

NameError: name 's1_e2' is not defined

- There is no solutions for both the systems.
    - The first system has extra variable as x3 only in one equation and absent from the other.
    - The second system has the third variable in both equations, but is lacking the third equation for the calculation.