# part 1
## 1. Create a note book to demonstrate the numpy operations

In [6]:
import numpy as np
import matplotlib.pyplot as plt 
from scipy import linalg

#create a numpy operations
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([1,2,3,4,5,6,7,8,9,10])

#addition
c = a + b
print("Addition of 2 arrays",c)

#subtraction
d = a - b
print("Sub of 2 arrays",d)

#multiplication
e = a * b
print("multiplication of 2 arrays",e)

#division
f = a / b
print("Division of 2 arrays",f)


#power  of 2    
g = a ** 2
print("Power of 2 of array A",g)

#power of 3
h = a ** 3
print("Power of 3 of array B",h)   

Addition of 2 arrays [ 2  4  6  8 10 12 14 16 18 20]
Sub of 2 arrays [0 0 0 0 0 0 0 0 0 0]
multiplication of 2 arrays [  1   4   9  16  25  36  49  64  81 100]
Division of 2 arrays [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Power of 2 of array A [  1   4   9  16  25  36  49  64  81 100]
Power of 3 of array B [   1    8   27   64  125  216  343  512  729 1000]


## 2.Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [7]:
Arr=np.arange(1,20,3)
print("Array Increment by 3 numbers ",Arr)

Array Increment by 3 numbers  [ 1  4  7 10 13 16 19]


In [8]:
# 3 .Create a new array of shape 3 with random numbers between 0 and 1.
Arr1=np.random.rand(3)
print("Created array with size of 3",Arr1)


Created array with size of 3 [0.83054459 0.66400538 0.88648282]


## 4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

In [9]:
arr2=np.array([[10,20,30],[30,12,16],[42,17,56]])
#print first two rows

print("Printing first two rows",arr2[:2])
# printi last two rows
print("Printing last two rows",arr2[1:])


Printing first two rows [[10 20 30]
 [30 12 16]]
Printing last two rows [[30 12 16]
 [42 17 56]]


In [10]:
#Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
arr3=np.array([[10,20],[30,40]])
arr4=np.array([[50,60],[70,80]])
print("Vertical stacking:\n",np.vstack((arr3,arr4)))
print("Horizontal stacking:\n",np.hstack((arr3,arr4)))
print("Splitting the arrays into smaller arrays:\n",np.hsplit(arr3,2))  
print("Splitting the arrays into smaller arrays:\n",np.vsplit(arr3,2))



Vertical stacking:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]
Horizontal stacking:
 [[10 20 50 60]
 [30 40 70 80]]
Splitting the arrays into smaller arrays:
 [array([[10],
       [30]]), array([[20],
       [40]])]
Splitting the arrays into smaller arrays:
 [array([[10, 20]]), array([[30, 40]])]


In [11]:
# Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?
X=np.array([[5,7,2],[4,5,6],[7,4,2]])
Y=np.array([[4,2],[6,2],[4,2]])
print("Multiplication of two matrices:\n",np.dot(X,Y))


Multiplication of two matrices:
 [[70 28]
 [70 30]
 [60 26]]


In [12]:
# Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
x=np.array([2,-1,-8])   
y=np.array([3,1,-2])
print("Shape of x:",x.shape)
print("Number of dimensions of vector x:",x.ndim)

res=x.reshape(3,1)
print("Reshaped array:",res)
res1=y.reshape(3,1)
print("Reshaped array:",res1.ndim)


Shape of x: (3,)
Number of dimensions of vector x: 1
Reshaped array: [[ 2]
 [-1]
 [-8]]
Reshaped array: 2


In [13]:
# How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.
#Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes.
# Create a 3x3 matrix   
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Create a 1x3 matrix
y = np.array([1,2,3])
# Subtract x and y
print("Subtraction of two matrices:\n",x-y)
# Multiply x and y
print("Multiplication of two matrices:\n",x*y)




Subtraction of two matrices:
 [[0 0 0]
 [3 3 3]
 [6 6 6]]
Multiplication of two matrices:
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


# part 2

## linear equation for find x1 and x2


In [14]:
import numpy as np
a= np.array([[2,3,-4],[1,-4,0]])
b=np.array([6,8.0])
x=np.linalg.solve(a,b)
x

LinAlgError: Last 2 dimensions of the array must be square

In [20]:
y1=np.array([[3,-4,5],[-1,2,-4]])
y2=np.array([10,8])
x=np.linalg.solve(y1,y2)
x
   


LinAlgError: Last 2 dimensions of the array must be square

##  to performing the this linear algerba equation we need a n*n array and here we have [2,3] array so unfortunately we would not get the actual result for both the given equations.