#### <span style='color:#30c9b5'> Student Name & ID: ARJUN KC(8773456)  </span>

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


### Part 1

#### 1) Create a Notebook to demonstrate NumPy Operations.

In [2]:
import numpy as np  #The Python package NumPy is used to manipulate arrays. Additionally, it contains matrices, Fourier transform, and functions for working in the area of linear algebra.

#### 2) Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [13]:
arj = np.arange(1,20,3)  # there are three arguments in arange() which is "start" =1, "stop"=20 and "step size"=3
arj

array([ 1,  4,  7, 10, 13, 16, 19])

#### 3)Create a new array of shape 3 with random numbers between 0 and 1.

In [18]:
arr = np.random.rand(3)
print(arr) # create the random number between 0 and 1 using random module of numpy() 
print(arr.shape)  # determine the shape of array using shape() from numpy

[0.70539113 0.90866113 0.02111375]
(3,)


#### 4) Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [22]:
arry = np.array([[10,20,45], [30,12,16], [42,17,56]])
arry  #this is the two dimension array

array([[10, 20, 45],
       [30, 12, 16],
       [42, 17, 56]])

In [31]:
print("First two rows:","\n",arry[0:2] ) #taking the first two of 2D array where indexing start from first row and stop at second row

First two rows: 
 [[10 20 45]
 [30 12 16]]


In [32]:
print("Last two row of 2D array:","\n",arry[1:]) # indexing start from second row and stop at last rows

Last two row of 2D array: 
 [[30 12 16]
 [42 17 56]]


#### 5)Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [62]:
arj1 = np.array([[3,4],[5,6]])  #first  2X2 array
arj2 = np.array([[7,8],[9,2]])  #second 2x2 array
vertical_stack_array = np.vstack((arj1,arj2)) # create the vertical stack of given 2 array
horizontal_stack_array = np.hstack((arj1,arj2)) # create the horizontal stack of given 2 array
vertical_split_array = np.vsplit(vertical_stack_array,2) # create the vertical split of given 2 array into smaller aaray
horizontal_split_array= np.hsplit(horizontal_stack_array,4) # create the horizontal split of given 2 array into smaller aaray
print("This is vertically stacked array of 2x2 Matrices:","\n",vertical_stack_array)
print("This is horizontally stacked array of 2x2 Matrices:","\n",horizontal_stack_array)
print("This is vertically splited array of 2x2 Matrices::","\n",vertical_split_array)
print("This is horizontally splited array of 2x2 Matrices:","\n",horizontal_split_array)



This is vertically stacked array of 2x2 Matrices: 
 [[3 4]
 [5 6]
 [7 8]
 [9 2]]
This is horizontally stacked array of 2x2 Matrices: 
 [[3 4 7 8]
 [5 6 9 2]]
This is vertically splited array of 2x2 Matrices:: 
 [array([[3, 4],
       [5, 6]]), array([[7, 8],
       [9, 2]])]
This is horizontally splited array of 2x2 Matrices: 
 [array([[3],
       [5]]), array([[4],
       [6]]), array([[7],
       [9]]), array([[8],
       [2]])]


#### 6)Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? Demonstrate the case when it is not possible to.

In [105]:
x = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
y = np.array([[4, 2], [6, 2], [4, 2]])
print(x.shape)
print(y.shape)

(3, 3)
(3, 2)


#### Yes, we can do multiplication of these two matrice but only uisng dot product or matmultiplication'''
####  -->np.dot(array a, array b): as it returns the scalar or dot product of two arrays'''
#### -->np.matmul(array a, array b): as it returns the matrix product of two arrays

In [102]:
arj_dot = np.dot(x,y)
print("Using dot product:","\n",arj_dot)
arj_mat = np.matmul(x,y)
print("Using matrix product:","\n",arj_mat)


Using dot product: 
 [[70 28]
 [70 30]
 [60 26]]
Using matrix product: 
 [[70 28]
 [70 30]
 [60 26]]


#### Below we have a case when it is not possible

#### But we can not do multiplication of these matrices using --> np.multiply(array a, array b): as it returns the element-wise matrix multiplication of two arrays

In [103]:
arj_mul = np.multiply(x,y)

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

#### because the number of columns in X (3) is not equal to the number of rows in Y (3). Matrix multiplication requires that the number of columns in the first matrix matches the number of rows in the second matrix.

#### 7) Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [131]:
x = np.array([2, -1, -8]) #given vector of x and y
y = np.array([3, 1, -2])

In [135]:
print("Initial Shape of Vector x:",x) # intial vector of x without changes
print("Initial dimension of vector x:",x.ndim) #gives the dimension of x vector
X = x.reshape(3,1) # #reshaping the vector of x to the given matrxi of (3,1)
print("Reshaping the vector x to (3,1):","\n",X) 
print("After reshaping, the shape of vector x:","\n",X.shape) # checking the shape of vector after changes
print("After reshaping, the dimension of vector X:",X.ndim) #checking the dimension of vector after reshaping

Initial Shape of Vector x: [ 2 -1 -8]
Initial dimension of vector x: 1
Reshaping the vector x to (3,1): 
 [[ 2]
 [-1]
 [-8]]
After reshaping, the shape of vector x: 
 (3, 1)
After reshaping, the dimension of vector X: 2


In [137]:
print("Initial Shape of Vector y:",y) # intial vector of y without changes
print("Initial dimension of vector y:",y.ndim) #gives the dimension of y vector
Y = y.reshape(3,1) #reshaping the vector of y to the given matrxi of (3,1)
print("Reshaping the vector y to (3,1):","\n",Y) 
print("After reshaping,the shape of vector y:","\n",Y.shape) # checking the shape of vector after changes
print("After reshaping, the dimension of vecto Y:",Y.ndim) #checking the dimension of vector after reshaping

Initial Shape of Vector y: [ 3  1 -2]
Initial dimension of vector y: 1
Reshaping the vector y to (3,1): 
 [[ 3]
 [ 1]
 [-2]]
After reshaping,the shape of vector y: 
 (3, 1)
After reshaping, the dimension of vecto Y: 2


#### 8)How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

#### The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.It simplifies operations by automatically adjusting the shape of arrays to make them compatible for element-wise operations.

#### Lets create  3x3 matrix

In [27]:
a_matx = np.array([[2,3,4],[5,6,7],[9,7,8]])
print("3X3 Matrice:","\n",a_matx)
print("Shape of 3X3 Matrice:","\n",a_matx.shape)


3X3 Matrice: 
 [[2 3 4]
 [5 6 7]
 [9 7 8]]
Shape of 3X3 Matrice: 
 (3, 3)


In [158]:
# Lets do Subraction using broadcasting
b_matx = 3
c_matx = a-b_matx #To match the matrix's form, the scalar value b_matx is automatically broadcasted. 
print("Subtraction of Matrix using broadcasting:","\n",c_matx)

Subtraction of Matrix using broadcasting: 
 [[-1  0  1]
 [ 2  3  4]
 [ 6  4  5]]


In [164]:
# Lets do Multiplication using broadcasting
d_matx = 5
Mul_matx = a*d_matx #To match the matrix's form, the scalar value d_matx is automatically broadcasted. 
print("Multiplication of Matrix using broadcasting:","\n",Mul_matx)

Multiplication of Matrix using broadcasting: 
 [[10 15 20]
 [25 30 35]
 [45 35 40]]


#### Part 2

#### Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. 

#### 1.2x1+3x2-4x3=6,x1-4x2=8
#### 2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [48]:
## 1. 2x1+3x2-4x3=6,x1-4x2=8
#A = [2,3,-4]
#B = [1,-4,0]
#C = ?
sys_1 = np.array([[2,3,-4],[1,-4,0]])
c = np.array([6,8])
print("The coeff of first linear system:",sys_1.shape)
print("The constant of first linear system:",c.shape)
lin_eqtn = np.linalg.solve(sys_1,c)#Solving a linear matrix equation, or system of linear scalar equations.
print(lin_eqtn)
       
# it will raise error as we have 3 different variable for x1,x2,x3 and we only have two equation so we need one more equation to compile it
# we need equal number of row and column ie square matrix to compute this equation.


The coeff of first linear system: (2, 3)
The constant of first linear system: (2,)


LinAlgError: Last 2 dimensions of the array must be square

In [50]:
# 2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8
# A = [3,-4,5]
# B = [-1,2,-4]
# C = ?
sys_2 = np.array([[3,-4,5],[1,2,-4]])
c2 = np.array([10,8])
print("The coeff of first linear system:",sys_2.shape)
print("The constant of first linear system:",c2.shape)
lin_eqtn = np.linalg.solve(sys_2,c2) #Solving a linear matrix equation, or system of linear scalar equations.
print(lin_eqtn)

# it will raise same error over here as we have 3 different variable for y1,y2,y3 and we only have two equation so we need one more equation to compile it
# we need equal number of row and column ie square matrix to compute this equation.
# LinAlgError: Last 2 dimensions of the array must be square

The coeff of first linear system: (2, 3)
The constant of first linear system: (2,)


LinAlgError: Last 2 dimensions of the array must be square