# Lab 1

# Kishankumar Sathvara (8900065)

## Part: 1

### 1. Create a Notebook to demonstrate NumPy Operations.

In [1]:
import numpy as np

### 2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
array = np.arange(1, 20, 3)
print(array)

[ 1  4  7 10 13 16 19]


### 3. Create a new array of shape 3 with random numbers between 0 and 1.

In [3]:
array1 = np.random.rand(3)
print(array1)

[0.52969384 0.66663191 0.15364685]


### 4. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations

In [4]:
array2 = np.array([[10,20,45], [30,12,16], [42,17,56]])
print(array2)

[[10 20 45]
 [30 12 16]
 [42 17 56]]


### Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows

In [5]:
print("First 2 rows\n",array2[:2])

print("Last 2 rows\n",array2[1:])

First 2 rows
 [[10 20 45]
 [30 12 16]]
Last 2 rows
 [[30 12 16]
 [42 17 56]]


### 5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [6]:
array3=np.array([[19,29],[39,49]])
array4=np.array([[59,69],[79,89]])

print("Vertical stacking:-", np.vstack((array3, array4)))

print("\n Horizontal stacking:", np.hstack((array3, array4)))

print("\n Splitting vertically:", np.vsplit(array3, 2))

print("\n Splitting horizontally:", np.hsplit(array3, 2))

Vertical stacking:- [[19 29]
 [39 49]
 [59 69]
 [79 89]]

 Horizontal stacking: [[19 29 59 69]
 [39 49 79 89]]

 Splitting vertically: [array([[19, 29]]), array([[39, 49]])]

 Splitting horizontally: [array([[19],
       [39]]), array([[29],
       [49]])]


### 6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?

In [7]:
A=np.array([[5,7,2],[4,5,6],[7,4,2]])
B=np.array([[4,2],[6,2],[4,2]])

print("Multiplication :\n",np.dot(A,B))

Multiplication :
 [[70 28]
 [70 30]
 [60 26]]


Here, we are able to multiply A and B matrices since they have the same raw and column values. However, we cannot multiply B with A because the column and raw values do not match.

### 7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.

In [8]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Shape of vector x: " ,x.shape)

print("Dimensions of vector x: ", x.ndim)

Shape of vector x:  (3,)
Dimensions of vector x:  1


### Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [9]:
x = x.reshape(3, 1)
y = y.reshape(3, 1)

print("Reshaped array x:\n", x)
print("Reshaped array y:\n", y)

print("Dimensions of x: ", x.ndim)
print("Dimensions of y: ", y.ndim)

Reshaped array x:
 [[ 2]
 [-1]
 [-8]]
Reshaped array y:
 [[ 3]
 [ 1]
 [-2]]
Dimensions of x:  2
Dimensions of y:  2


### 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

The word "broadcasting" refers to how Numpy handles information in various formats when doing math operations. Whenever a math operation is performed on a grid, Numpy vectorizes the described case by iterating through the lattice component by component.

In [10]:
X = np.array([[19, 29, 39], [49, 59, 69], [79, 89, 99]])
Y = 5

print("Subtraction:\n", X - Y)

print("Multiplication:\n", X * Y)

Subtraction:
 [[14 24 34]
 [44 54 64]
 [74 84 94]]
Multiplication:
 [[ 95 145 195]
 [245 295 345]
 [395 445 495]]


# Part:2

### 1. Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions.
        

#### 2x1+3x2-4x3=6,x1-4x2=8
#### 3y1-4y2+5y3=10,-y1+2y2-4y3=8

For the first equation, we have variables represented by x and y. The first set of equations involves three variables (x1, x2, x3) and two variables (y1, y2) in the second set. To find a solution, we need at least three variables in the second set of equations. However, the dimensions of the two sets of equations are not compatible. In order to determine a solution, the dimensions of the equations should match, such as having a 2x2 or 3x3 system.

Also we cannot take any random number to solve the equation.

In [11]:
A = np.array([[2,3],[1,-4]])

B = np.array([6,8])

print('solution : ', np.linalg.solve(A, B))

solution :  [ 4.36363636 -0.90909091]


We are able to solve this equation because the dimension is (2*2)

For the second equation, we use the same method we use in first equation to get solution.

In [12]:
A = np.array([[3, -4, 5], [-1, 2, 4],[3, -2, 0]])

B = np.array([10,8, 12])

print('solution :',np.linalg.solve(A,B))

solution : [7.09090909 4.63636364 1.45454545]
