# Part-A

## 1. Creating an Array



In [4]:
### Create an array that starts from 1, ends at 20, incremented by 3.


import numpy as np

arr = np.arange(1, 21, 3)


In [5]:
print(arr)

[ 1  4  7 10 13 16 19]


# 2. Generating Random Numbers
Create a new array of shape 3 with random numbers between 0 and 1.

In [33]:
import random

random_array = []
for _ in range(3):
    random_number = random.random()
    random_array.append(random_number)
print (random_array)

[0.14205799987894907, 0.5619076475756867, 0.003334765091173475]


# 3. Slicing a 2D Array
Create a 2D array and perform slicing operations.

In [7]:
arr_2d = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("Original Array:")
print(arr_2d)



Original Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]


In [8]:
# Slice the 2D array to get the first two rows
first_two_rows = arr_2d[:2]
print("First Two Rows:")
print(first_two_rows)



First Two Rows:
[[10 20 45]
 [30 12 16]]


In [35]:
# Slice the 2D array to get the last two rows
last_two_rows = arr_2d[-2:]
print("Last Two Rows:")
print(last_two_rows)

Last Two Rows:
[[30 12 16]
 [42 17 56]]


# 4. Stacking and Splitting Arrays
Create two 2x2 arrays and demonstrate stacking and splitting operations.

In [20]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])





In [21]:
print(arr1)
print("     ")
print(arr2)

[[1 2]
 [3 4]]
     
[[5 6]
 [7 8]]


In [22]:
# Stack the arrays vertically
vertical_stack = np.vstack((arr1, arr2))
print("Vertical Stack:")
print(vertical_stack)

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
# Stack the arrays horizontally
horizontal_stack = np.hstack((arr1, arr2))
print("Horizontal Stack:")
print(horizontal_stack)


Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


In [23]:

# Split the arrays into smaller arrays
split_arr = np.hsplit(horizontal_stack, 2)
print("Split Arrays:")
print(split_arr)

Split Arrays:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# 5. Matrix Multiplication
Perform matrix multiplication between two matrices.

In [15]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])



In [18]:
print(X)
print("     ")
print(Y)

[[5 7 2]
 [4 5 6]
 [7 4 2]]
     
[[4 2]
 [6 2]
 [4 2]]


In [19]:
# Perform matrix multiplication
result = np.dot(X, Y)
print("Matrix Multiplication Result:")
print(result)

Matrix Multiplication Result:
[[70 28]
 [70 30]
 [60 26]]


# 6. Reshaping Arrays
Reshape arrays and determine the number of dimensions.

In [24]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Find the shape and number of dimensions of vector x
print("Shape of x:", x.shape)
print("Number of dimensions of x:", x.ndim)



Shape of x: (3,)
Number of dimensions of x: 1


In [25]:
# Reshape vector x to a matrix of size (3,1)
x_reshaped = x.reshape((3, 1))
print("Reshaped x:")
print(x_reshaped)
print("Number of dimensions after reshaping x:", x_reshaped.ndim)



Reshaped x:
[[ 2]
 [-1]
 [-8]]
Number of dimensions after reshaping x: 2


In [26]:
# Reshape vector y to a matrix of size (3,1)
y_reshaped = y.reshape((3, 1))
print("Reshaped y:")
print(y_reshaped)
print("Number of dimensions after reshaping y:", y_reshaped.ndim)

Reshaped y:
[[ 3]
 [ 1]
 [-2]]
Number of dimensions after reshaping y: 2


# 7. Broadcasting
Demonstrate broadcasting with a 3x3 matrix.

In [ ]:
Broadcasting is a NumPy method that allows arrays of various forms to be utilised in arithmetic calculations. 
It makes it easier to conduct element-wise operations on arrays of various sizes.
Broadcasting in NumPy adheres to a series of principles to align the shapes of the arrays involved in the operation. 
The following are the rules:

1. If the dimensions of the arrays disagree, the array with fewer dimensions is padded with ones on its left side until the dimensions match.
2. an error is raised if the form of any dimension of the two arrays differs and is not equal to 1.
3. Arrays are compatible and may be used if the sizes in each dimension are either equal or one of them is 1.

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])

print("matrix a",a)
print("        ")
print("matrix b",b)


matrix a [[1 2 3]
 [4 5 6]
 [7 8 9]]
        
matrix b [1 2 3]


In [38]:
# Perform subtraction using broadcasting
subtraction_result = a - b
print("Subtraction Result:")
print(subtraction_result)



Subtraction Result:
[[0 0 0]
 [3 3 3]
 [6 6 6]]


In [39]:
# Perform multiplication using broadcasting
multiplication_result = a * b
print("Multiplication Result:")
print(multiplication_result)

Multiplication Result:
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


# Part-B

## X Coordinates

In [59]:
# Coefficient matrix
A = np.array([[2, 3, -4],
              [1, -4, 0]])


print(A)

[[ 2  3 -4]
 [ 1 -4  0]]


In [61]:
# Convert A to a 2x2 matrix
A = A[:2, :2]
print(A)

[[ 2  3]
 [ 1 -4]]


In [62]:
B=np.array([6,8])
print(B)

[6 8]


In [64]:

X=np.linalg.solve(A,B)

In [65]:
print("x1 is  ",X[0])
print("x2 is  ",X[1])

x1 is   4.363636363636363
x2 is   -0.9090909090909091


## Y Cordinates

In [66]:
A2 = np.array([[3, -4, 5],
               [-1, 2, -4]])
print(A2)

[[ 3 -4  5]
 [-1  2 -4]]


In [68]:
B2=np.array([10,8])
print(B2)

[10  8]


In [73]:
shape_=A2.shape
arr = np.empty(shape_)

# Check if the last two dimensions are square
if shape_[-1] == shape_[-2]:
    print("Last two dimensions are square.")
else:
    print("Last two dimensions are not square.")

Last two dimensions are not square.


In [74]:
A2=A2[:,:2]

In [75]:
A2

array([[ 3, -4],
       [-1,  2]])

In [76]:
Y=np.linalg.solve(A2,B2)

In [77]:
print("y1 is  ",Y[0])
print("y2 is  ",Y[1])

y1 is   26.0
y2 is   17.0
