## Lab 1 – Basic NumPy Operations 

### Student Name : Ramya Chandran
### Student Number : 8895789

### PART A

#### 1.Create a Notebook to demonstrate NumPy Operations.

In [35]:
import numpy as np

#### 2.Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [36]:
arr_1 = np.arange(1, 20, 3)
arr_1

array([ 1,  4,  7, 10, 13, 16, 19])

#### 3.Create a new array of shape 3 with random numbers between 0 and 1.

In [37]:
arr_2 = np.random.random(3)
print(arr_2)

[0.35531666 0.68402037 0.58132769]


#### 4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 

#### Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [38]:
# Create a 2D array
arr_3 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# Slice the 2D array to get the first two rows
first_two = arr_3[:2, :]
print("First two rows:")
print(first_two)

# Slice the 2D array to get the last two rows
last_two = arr_3[1:, :]
print("Last two rows:")
print(last_two)

First two rows:
[[10 20 45]
 [30 12 16]]
Last two rows:
[[30 12 16]
 [42 17 56]]


#### 5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [39]:
# Create two 2x2 arrays
arr_4 = np.array([[1, 2], [3, 4]])
arr_5 = np.array([[5, 6], [7, 8]])

# Stack arrays vertically
ver_stack = np.vstack((arr_4, arr_5))
print("Vertical stack:")
print(ver_stack)

# Stack arrays horizontally
hori_stack = np.hstack((arr_4, arr_5))
print("Horizontal stack:")
print(hori_stack)

# Split arrays into smaller arrays
split_ver = np.vsplit(ver_stack, 2)
print("Split vertically:")
for sub_array in split_ver:
    print(sub_array)

split_hori = np.hsplit(hori_stack, 2)
print("Split horizontally:")
for sub_array in split_hori:
    print(sub_array)


Vertical stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack:
[[1 2 5 6]
 [3 4 7 8]]
Split vertically:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Split horizontally:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


#### 6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 

#### Demonstrate the case when it is not possible to.

In [40]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

print("Shape of X: ", X.shape)
print("Shape of Y: ", Y.shape)

print("The Matrix Multiplication of X * Y is \n", np.matmul(X, Y))
# print("The Matrix Multiplication of X * Y is \n", np.matmul(Y, X))

Shape of X:  (3, 3)
Shape of Y:  (3, 2)
The Matrix Multiplication of X * Y is 
 [[70 28]
 [70 30]
 [60 26]]


Here the matrix multiplication of X * Y is possible since the number of columns of the first matrix and number of rows of thr second matrix are the same which is 3. So np.matmul provides an answer.

When we try Y * X it throws an error since the number of columns in Y is 2 and number of rows in X is 3 so the matrix multiplication is not possible.

####  7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.

#### Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [41]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Find the shape and number of dimensions of vector x
print("Print the vector x: ", x)
print("Shape of vector x:", x.shape)
print("Number of dimensions of vector x:", x.ndim)

# Reshape vector x and y to a matrix of size (3, 1) in two methods
x_reshaped = x.reshape(3, 1)
y_reshaped = np.reshape(y, (3, 1))

# Find the shape and number of dimensions of vector x
print("Print the x_reshaped: ", x_reshaped)
print("Shape of vector x_reshaped:", x_reshaped.shape)
print("Number of dimensions of vector x_reshaped:", x_reshaped.ndim)
print("Print the y_reshaped: ", y_reshaped)
print("Shape of vector y_reshaped:", y_reshaped.shape)
print("Number of dimensions of vector y_reshaped:", y_reshaped.ndim)


Print the vector x:  [ 2 -1 -8]
Shape of vector x: (3,)
Number of dimensions of vector x: 1
Print the x_reshaped:  [[ 2]
 [-1]
 [-8]]
Shape of vector x_reshaped: (3, 1)
Number of dimensions of vector x_reshaped: 2
Print the y_reshaped:  [[ 3]
 [ 1]
 [-2]]
Shape of vector y_reshaped: (3, 1)
Number of dimensions of vector y_reshaped: 2


After reshaping the vector array of one dimension is changed to the 2d matrix with dimension 2

#### 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [42]:
# Create a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Perform subtraction using broadcasting
subtraction_result = matrix - 2
print("Subtraction result:")
print(subtraction_result)

# Perform multiplication using broadcasting
multiplication_result = matrix * [1, 2, 3]
print("Multiplication result:")
print(multiplication_result)

Subtraction result:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
Multiplication result:
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


Subtraction : Broadcasting is used to subtract the scalar value 2 from each matrix member. The scalar 2 is implicitly broadcasted to all element in order to take the form of the matrix.

Multiplication : In order to fit the geometry of the matrix, broadcasting extends the 1D array along the rows, enabling element-wise multiplication.

### Part B 

#### 1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. 
* 2x1+3x2-4x3=6,x1-4x2=8
* 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [43]:
# Lets solve first set with X1, X2, X3
A = np.array([[2, 3, -4], [1, -4, 0]])
B = np.array([[6], [8]])

# Solve the system of equations
#np.linalg.solve(A, B)
print(A.shape)
print(B.shape)



(2, 3)
(2, 1)


In [44]:
# Lets solve second set y1, y2, y3
A = np.array([[3, -4, 5], [-1, 2, -4]])
B = np.array([[10], [8]])

# Solve the system of equations
#np.linalg.solve(A, B)
print(A.shape)
print(B.shape)


(2, 3)
(2, 1)


Here both the set of equations doesnot contain the required number of equations. The coeffients to be found are 3 variables but the equations given is just 2. Number of equations should match the number of variables. 