## Part A

In [2]:
import numpy as np

2.Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [3]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

 3.Create a new array of shape 3 with random numbers between 0 and 1.

In [4]:
np.random.rand(3,1)

array([[0.92206876],
       [0.13280067],
       [0.98335269]])

  4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
  Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [25]:
np2dArray = np.array([[10,20,45], [30,12,16], [42,17,56]])
slice1 = np2dArray[:2,]
print(f'First slice \n{slice1}')

print(f'Second slice \n{np2dArray[1:3, ]}')

First slice 
[[10 20 45]
 [30 12 16]]
Second slice 
[[30 12 16]
 [42 17 56]]


5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [6]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[20,30], [40,50]])

vArr = np.vstack((arr1, arr2))
print(vArr)
print()
hArr = np.hstack((arr1, arr2)) 
print(hArr)

[[ 1  2]
 [ 3  4]
 [20 30]
 [40 50]]

[[ 1  2 20 30]
 [ 3  4 40 50]]


In [7]:
np.split(vArr, 2, axis=0)

[array([[1, 2],
        [3, 4]]),
 array([[20, 30],
        [40, 50]])]

In [8]:
np.split(hArr, [1,2,3], axis=1)

[array([[1],
        [3]]),
 array([[2],
        [4]]),
 array([[20],
        [40]]),
 array([[30],
        [50]])]

6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
Demonstrate the case when it is not possible to.

In [9]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

print(X.shape)
print(Y.shape)

(3, 3)
(3, 2)


> An (3, 3) matrix can be multiplied by a (3, 2) matrix. The column number of first matrix should be equal to the row number of second matrix. Therefore,
X . Y has a solution but Y . X has not a solution.

In [10]:
# (m, n) x (n, p) --> (m, p)

X @ Y

array([[70, 28],
       [70, 30],
       [60, 26]])

In [11]:
Y @ X

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [12]:
x = np.array([2, -1, -8]) 
y = np.array([3, 1, -2])

In [13]:
print(f'Shape of x : {x.shape}')
print(f'Number of dimensions in x : {x.ndim}')
print(f'Shape of y : {y.shape}')
print(f'Number of dimensions in y : {y.ndim}')

Shape of x : (3,)
Number of dimensions in x : 1
Shape of y : (3,)
Number of dimensions in y : 1


In [14]:
x = np.reshape(x, (3, 1))
print(f'Shape of x : {x.shape}')
print(f'Number of dimensions in x : {x.ndim}')

y = np.reshape(y, (3,1))
print(f'Shape of y : {y.shape}')
print(f'Number of dimensions in y : {y.ndim}')

Shape of x : (3, 1)
Number of dimensions in x : 2
Shape of y : (3, 1)
Number of dimensions in y : 2


8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

> Broadcasting in Numpy enables to perform elementwise addition, subtraction and multiplication on arrays of different sizes. Numpy achieves it by applying three rules on arrays:

    . Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
    . Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
    . Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.



In [15]:
# Examples
a = np.array([3, 5, 7])
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
a + b

array([[4., 6., 8.],
       [4., 6., 8.],
       [4., 6., 8.]])

In [17]:
# Multiplication with a scalar
c = 5

c * b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [18]:
# Element wise multiplication
a = np.array([3, 5, 7])
d = np.array([[2,4,6],[15,20,25],[1,2,3]])

a * d

array([[  6,  20,  42],
       [ 45, 100, 175],
       [  3,  10,  21]])

In [19]:
#Subtraction
a - b

array([[2., 4., 6.],
       [2., 4., 6.],
       [2., 4., 6.]])

In [ ]:
# Rule 3
M = np.ones((3, 2))
a = np.arange(3)

M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

# Part B

1. 
    2x1+3x2-4x3=6 <br>
    x1-4x2=8
A = [[2,3,-4],[1,-4,0]]
B = [6, 8]
Ax = B

By using these linear equations, it is not possible to find a solution, because there should be one more linear equation to solve. There are 3 variables, but 2 linear equations. 
Also we can check whether there is a solution, if exists, how many solutions we have by calculating determinant of matrix A. But, A should be a square matrix. Therefore, we canot see the number of solutions.

In [20]:
A = np.array([[2,3,-4],[1,-4,0]])
B = np.array([6,8])

print(A.shape)
print(B.shape)

(2, 3)
(2,)


2. 3y1-4y2+5y3=10 <br>
    -y1+2y2-4y3=8
    Again, we cannot solve this linear equation system because we need one more equation to find solution for y1, y2 and y3.

Ax = B <br>

A = [[3, -4, 5],[-1, 2, -4]] <br>
B = [[10 ,8]]

In [21]:
A = np.array([[3, -4, 5],[-1, 2, -4]])
B = np.array([[10 ,8]])
np.linalg.solve(A, B)

LinAlgError: Last 2 dimensions of the array must be square

As you see from the error, there should be one more equation to obtain square maxrix.