### Lab 1 – Basic NumPy Operations 
#### Student Name : Aswani P U
#### Student Id : 8858117

#### Part A
1.Create a Notebook to demonstrate NumPy Operations.


In [2]:
# Import numpy package
import numpy as np

 2.Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [3]:
int_array = np.arange(1,20,3) 
int_array

array([ 1,  4,  7, 10, 13, 16, 19])

3.Create a new array of shape 3 with random numbers between 0 and 1.

In [4]:
np.random.rand(3)

array([0.94429921, 0.89996506, 0.34751065])

4 . Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [5]:
# Create 2D array
original_array = np.array([[10,20,45], [30,12,16], [42,17,56]]) 
print("2D array : \n", original_array)

# Slice first two rows
first_two_rows = original_array[0:2]
print("First 2 rows of Array : \n", first_two_rows)

# Slice last two rows
last_two_rows =original_array[-2:,:]
print("Last two rows : \n", last_two_rows)

2D array : 
 [[10 20 45]
 [30 12 16]
 [42 17 56]]
First 2 rows of Array : 
 [[10 20 45]
 [30 12 16]]
Last two rows : 
 [[30 12 16]
 [42 17 56]]


5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [6]:
# Create 2x2 arrays
arr_1 = np.array([[24,25],[34,35]])
arr_2 = np.array([[44,45],[45,46]])

# Stack arrays horizontally
h_array = np.hstack([arr_1,arr_2])
print("The horizontally stacked array : \n", h_array)

# Stack vertically
v_array = np.vstack([arr_1,arr_2])
print("The vertically stacked array : \n", v_array)

# Split the h_array
sp_h_array = np.array_split(h_array, indices_or_sections = 4, axis = 1) 
print("Splitted  h_array : \n", sp_h_array)

# Split v_array
sp_v_array = np.array_split(v_array, indices_or_sections=2, axis = 0) 
print("Splitted v_array : \n", sp_v_array)

The horizontally stacked array : 
 [[24 25 44 45]
 [34 35 45 46]]
The vertically stacked array : 
 [[24 25]
 [34 35]
 [44 45]
 [45 46]]
Splitted  h_array : 
 [array([[24],
       [34]]), array([[25],
       [35]]), array([[44],
       [45]]), array([[45],
       [46]])]
Splitted v_array : 
 [array([[24, 25],
       [34, 35]]), array([[44, 45],
       [45, 46]])]


 6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 

In [7]:
# Create matrices
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Multiply X and Y matrices
Z = np.matmul(X, Y) 
print("Result: \n", Z)

Result: 
 [[70 28]
 [70 30]
 [60 26]]


6. b) Demonstrate the case when it is not possible to.
   
   Ans : To multiply 2 matrices number of columns in first matrix should be  equal to the number of rows in second matrix.
         So, we can not multiply Y & X.

In [8]:
# Multiply Y and X matrices
M = np.matmul(Y, X) 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [ ]:
# Create arrays
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])
print("X : \n", X)
print("Y : \n", Y)

# Find the shape and dimension of x
print("x shape : \n", x.shape)
print("x dimension : \n", x.ndim)

# Reshape the vector x and y to a matrix of size (3,1)
new_x = x.reshape(3,1)
new_y = y.reshape(3,1)
print("Reshaped X: \n", new_x)
print("Reshaped y: \n", new_y)

# Find the dimension of reshaped Y
print("Reshaped Y dimension : \n", new_y.ndim)

X : 
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
Y : 
 [[4 2]
 [6 2]
 [4 2]]
x shape : 
 (3,)
x dimension : 
 1
Reshaped X: 
 [[ 2]
 [-1]
 [-8]]
Reshaped y: 
 [[ 3]
 [ 1]
 [-2]]
Reshaped Y dimension : 
 2


 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

 Broadcasting help to perform operations on arrays with different shapes.

In [ ]:
X = np.array ([[12, 13, 14],
               [15, 16, 17],
               [18, 19, 20]])
Y = 5

# Substraction 
S = X-Y
print("Substraction Result : \n", S)

# Multiplication of matrix
M = X*Y
print("Multiplication Result : \n", M)

Substraction Result : 
 [[ 7  8  9]
 [10 11 12]
 [13 14 15]]
Multiplication Result : 
 [[ 60  65  70]
 [ 75  80  85]
 [ 90  95 100]]


 9. Add Markdown text, with a headline, that provides a very brief overview of the graphs (e.g., one sentence for each). 
    Feel free to add additional Markdown elements (description/additional comments)

#### Part B
   1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and 
     determine the number of solutions using the functions. 
	         1.2x1+3x2-4x3=6,x1-4x2=8
		
	         2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8


In [ ]:
# Create feature matrix - 2x1+3x2-4x3=6,x1-4x2=8
X= np.array([[2,3,-4],[1,-4,0]])

# Create constants matrix 
Y = np.array([6,8])

print("Matrix X shape: \n", X.shape)
print("Matrix Y shape : \n", Y.shape)

np.linalg.solve(X,Y)

Matrix X shape: 
 (2, 3)
Matrix Y shape : 
 (2,)


LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
# Create feature matrix  - 3y1-4y2+5y3 = 10; -y1+2y2-4y3 = 8
A = np.array([[3,-4,5],[-1,2,-4]])

# Create constants matrix 
B = np.array([10,8])

print("Matrix A shape: \n", A.shape)
print("Matrix B shape : \n", B.shape)
np.linalg.solve(X,Y)

Matrix A shape: 
 (2, 3)
Matrix B shape : 
 (2,)


LinAlgError: Last 2 dimensions of the array must be square

From the shape, it's clear that we can not find a solution for these equations. Determinant is used to find the number of solutions of a matrix. We can calculate the determinant of a matrix only if it's a square matrix.  But here, it's not a square matrix.