<h1 align = 'center'><B><U>Lab 1 - Basic NumPy Operations</U></B></h1>
<h3 align = 'center'><B>Waseem Iqbal Shaikh (8902834)</B></h3>

<h3 align = 'center'><B><U>Part A</U></B></h3>

<h3><I><U>1. Create a Notebook to demonstrate NumPy Operations.</U></I></h3>

In [132]:
import numpy as np

<h3><I><U>2. Create an array that starts from the integer 1, ends at 20, incremented by 3.</U></I></h3>

In [133]:
array1 = np.arange(1,20,3)
array1

array([ 1,  4,  7, 10, 13, 16, 19])

<h3><I><U>3. Create a new array of shape 3 with random numbers between 0 and 1.</U></I></h3>

In [134]:
array2 = np.random.rand(3,3)
print ("New array of shape 3 with random numbers between 0 and 1:-\n", array2)

New array of shape 3 with random numbers between 0 and 1:-
 [[0.09705046 0.33198608 0.75071507]
 [0.68645698 0.44923455 0.06083376]
 [0.70109017 0.31067397 0.68795517]]


<h3><I><U>4. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:<br><br></U>Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.</I></h3>

In [135]:
array3 = np.array([[10,20,45], [30,12,16], [42,17,56]])
print("The first two rows of the 2D array:-\n", array3[0:2])
print("The last two rows of 2D array:-\n", array3[1:3])

The first two rows of the 2D array:-
 [[10 20 45]
 [30 12 16]]
The last two rows of 2D array:-
 [[30 12 16]
 [42 17 56]]


<h3><I><U>5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.</U></I></h3>

In [136]:
array4 = [[1,6],[1,1]]
array5 = [[1,9],[9,7]]
print("Two arrays of 2x2:-\n", array4, "\n", array5)
verticalStack = np.vstack((array4,array5))
print("Stacking elements vertically:-\n", verticalStack)
horizontalStack = np.hstack((array4, array5))
print("Stacking elements horizontally:-\n", horizontalStack)
print("Splitting the arrays in smaller arrays:-")
jointArray = np.concatenate((array4,array5),axis=None)
print(np.split(jointArray,jointArray.size))

Two arrays of 2x2:-
 [[1, 6], [1, 1]] 
 [[1, 9], [9, 7]]
Stacking elements vertically:-
 [[1 6]
 [1 1]
 [1 9]
 [9 7]]
Stacking elements horizontally:-
 [[1 6 1 9]
 [1 1 9 7]]
Splitting the arrays in smaller arrays:-
[array([1]), array([6]), array([1]), array([1]), array([1]), array([9]), array([9]), array([7])]


<h3><I><U>6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? Demonstrate the case when it is not possible to.</U></I></h3>

In [137]:
X = ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = ([[4, 2], [6, 2], [4, 2]])
print("Yes, the multiplication of X and Y array is possible because number of columns of X is equal to number of rows of Y. The multiplication of X and Y:-\n", np.matmul(X,Y))
print("The multiplication of Y and X is not possible because the number of columns of Y array is not equal to number of rows in X array. You can only multiply two matrices if their dimensions are compatible , which means the number of columns in the first matrix is the same as the number of rows in the second matrix. Below is the example of error that you will receive.:-")
print("The multiplication of X and Y array:-\n", np.matmul(Y,X))


Yes, the multiplication of X and Y array is possible because number of columns of X is equal to number of rows of Y. The multiplication of X and Y:-
 [[70 28]
 [70 30]
 [60 26]]
The multiplication of Y and X is not possible because the number of columns of Y array is not equal to number of rows in X array. You can only multiply two matrices if their dimensions are compatible , which means the number of columns in the first matrix is the same as the number of rows in the second matrix. Below is the example of error that you will receive.:-


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

<h3><I><U>7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).</U></I></h3>

In [ ]:
x = ([2, -1, -8])
y = ([3, 1, -2])
xArray = np.array(x)
yArray = np.array(y)
print("The shape of x and y array:-")
print("The shape of x:", xArray.shape)
print("The shape of y:", yArray.shape)
print("The dimensions of x and y:-")
print("Dimension of x:", xArray.ndim)
print("Dimension of y:", yArray.ndim)
print("Reshaping x array to (3,1) matrix:-")
print(xArray.reshape((3,1)))
print("Reshaping y array to (3,1) matrix:-")
yReshape = yArray.reshape((3,1))
print(yReshape)
print("Dimension of reshaped y array:", yReshape.ndim)


The shape of x and y array:-
The shape of x: (3,)
The shape of y: (3,)
The dimensions of x and y:-
Dimension of x: 1
Dimension of y: 1
Reshaping x array to (3,1) matrix:-
[[ 2]
 [-1]
 [-8]]
Reshaping y array to (3,1) matrix:-
[[ 3]
 [ 1]
 [-2]]
Dimension of reshaped y array: 2


<h3><I><U>8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.</U></I></h3>

In [ ]:
print("The way NumPy handles arrays with various shapes while performing arithmetic operations is known as broadcasting. Broadcasting is done between arrays of different dimensions.")
array6 = np.array([[2,7,1],[4,1,9],[9,4,3]])
subtraction = array6 - 3
multiplication = array6 * 3
print("\n\nLet us consider the below array:")
print(array6)
print("\n\nThe subtraction of ", array6, "- 3 is \n\n", subtraction)
print("\n\nThe multiplication of", array6, "* 3 is \n\n", multiplication)

The way NumPy handles arrays with various shapes while performing arithmetic operations is known as broadcasting. Broadcasting is done between arrays of different dimensions.


Let us consider the below array:
[[2 7 1]
 [4 1 9]
 [9 4 3]]


The subtraction of  [[2 7 1]
 [4 1 9]
 [9 4 3]] - 3 is 

 [[-1  4 -2]
 [ 1 -2  6]
 [ 6  1  0]]


The multiplication of [[2 7 1]
 [4 1 9]
 [9 4 3]] * 3 is 

 [[ 6 21  3]
 [12  3 27]
 [27 12  9]]


<h3 align = "center">Part B<B><U></U></B></h3>

<h3><I><U>1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions.</U><br><br>a. 2x1+3x2-4x3=6,x1-4x2=8</I></h3>

In [ ]:
coefficientArray = np.array([[2,3,-4],[0,1,-4]])
constantArray = np.array([6,8])
results = np.linalg.solve(coefficientArray,constantArray)

LinAlgError: Last 2 dimensions of the array must be square

<h3>The coefficient matrix must have the same number of rows and columns for the linear system to be solvable. The number of coefficients of both the equation is not the same and so we cannot have a square coefficient matrix. Hence, we cannot find a solution for these equations.</h3>

<h3><I>b. 3y1-4y2+5y3=10,-y1+2y2-4y3=8</I></h3>

In [ ]:
coefficientArray = np.array([[3,4,5],[-1,2,-4]])
constantArray = np.array([10,8])
results = np.linalg.solve(coefficientArray,constantArray)

LinAlgError: Last 2 dimensions of the array must be square

<h3>The above equations are not solvable because the coefficient matrix is not a square matrix. We need one more equation to have a square coefficient matrix.</h3>