# Raghavendra Deshmukh - 8854506

### Demonstrate NumPy Operations

## Part - 1

In [2]:
import numpy as np
from numpy import random


### 2. Create an array that starts from the integer 1, ends at 20, incremented by 3

In [17]:
V= np.arange(1,20,3)
V

array([ 1,  4,  7, 10, 13, 16, 19])

### 3. Create a new array of shape 3 with random numbers between 0 and 1.

In [19]:
random_array = random.random(3)
print(random_array)

[0.77613128 0.74807351 0.55377418]


### 4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 

   Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [21]:
two_dim_arr = np.array([[10,20,45],[30,12,16],[42,17,56]])
multi_dim_arr = np.reshape(two_dim_arr,(3,3))
print(multi_dim_arr)

[[10 20 45]
 [30 12 16]
 [42 17 56]]


In [32]:
print(multi_dim_arr[:2],end='\n\n') # 1st two rows
print(multi_dim_arr[1:]) # last two rows

[[10 20 45]
 [30 12 16]]

[[30 12 16]
 [42 17 56]]


### 5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [33]:
my_array1 = np.array ([[4,6],[3,6]])
my_array2 = np.array ([[3,1],[9,2]])

In [48]:
#stacking the elements vertically

vs = np.vstack((my_array1,my_array2))
hs = np.hstack((my_array1,my_array2))
print('Vertical stack \n',vs,end='\n')
print('Horizontal stack \n',hs,end='\n')

Vertical stack 
 [[4 6]
 [3 6]
 [3 1]
 [9 2]]
Horizontal stack 
 [[4 6 3 1]
 [3 6 9 2]]


Splitting the arrays into smaller arrays

In [52]:
np.hsplit(hs,4)

[array([[4],
        [3]]), array([[6],
        [6]]), array([[3],
        [9]]), array([[1],
        [2]])]

In [49]:
np.hsplit(vs,2)

[array([[4],
        [3],
        [3],
        [9]]), array([[6],
        [6],
        [1],
        [2]])]

### 6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 

Yes, we can multiply the matrices as shown below

In [53]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

In [56]:
# few ways that we can do
X.dot(Y) # method 1
X@Y # method 2

array([[70, 28],
       [70, 30],
       [60, 26]])

###  7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.

  Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [57]:
a = np.array([2,-1,-8])
b = np.array([3,1,-2])

(array([ 2, -1, -8]), array([ 3,  1, -2]))

In [60]:
print(a.shape) # shape of a matrix
print(b.shape)
print(a.ndim) # Dimension of a matrix
print(b.ndim)

(3,)
(3,)
1
1


In [68]:
# Reshaping the matrix
a = a.reshape(3,1)
b = b.reshape(3,1)

In [71]:
print(a,'\n\n',b)

[[ 2]
 [-1]
 [-8]] 

 [[ 3]
 [ 1]
 [-2]]


### 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [78]:
import numpy as np

# Creating a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Broadcasting multiplication with a single value
multiplication_result = matrix * 2
print('Matrix after multiplication\n',multiplication_result)

print("\n")
# Broadcasting subtraction with a single value
subtraction_result = matrix - 2
print("Matrix after subtraction\n",subtraction_result)

Matrix after multiplication
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Matrix after subtraction
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


     1.Create a Notebook to demonstrate NumPy Operations.
     
     2.Create an array that starts from the integer 1, ends at 20, incremented by 3.
     
     3.Create a new array of shape 3 with random numbers between 0 and 1.
     
     4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
     
       Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.
       
     5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
     
     6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
     
      Demonstrate the case when it is not possible to.
      
     7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
     
      Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).
      
     8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.
     
     9. Add Markdown text, with a headline, that provides a very brief overview of the graphs (e.g., one sentence for each). 
     
        Feel free to add additional Markdown elements (description/additional comments)
        
  10. Push the notebook to your lab-submission fork, and create a PR

# Part - 2

In [4]:
eq1 = np.array([[2,3,-4],[1,-4,0]])
eq2 = np.array([6,8])
print("The shape of eq1 matrix is: \n",eq1.shape)
print("The shape of eq2 matrix is: \n",eq2.shape)
#Finding x 
x = np.linalg.solve(eq1,eq2)

The shape of eq1 matrix is: 
 (2, 3)
The shape of eq2 matrix is: 
 (2,)


LinAlgError: Last 2 dimensions of the array must be square

The shape of matrix EQ1 is 2x3 which is a non-square matrix, Determinant cannot be calculated. Therefore we cannot inverse the matrix.
To find the solution matrix [x1, x2, x3], we need to find the inverse of A multiply with matrix B. Hence it is not possible.


In [6]:
eq3 = np.array([[3,-4,5],[-1,2,-3]])
eq4 = np.array([10, 8])
print("The shape of eq3 matrix is: \n", eq3.shape)
print("The shape of eq4 matrix is: \n", eq4.shape)
x2 = np.linalg.solve(eq3, eq4)

The shape of eq3 matrix is: 
 (2, 3)
The shape of eq4 matrix is: 
 (2,)


LinAlgError: Last 2 dimensions of the array must be square

Same with the shape of 2nd equation the matrix A is 2x3 which is a non-square matrix, determinant cannot be calculated. Hence we cannot inverse the matrix.
To find the solution matrix [x1, x2, x3], we need to find the inverse of A multiply with matrix B. Hence it is not possible.
