## LAB-1
### Name: Harshitha Anishetty
### StudenID: 8903318

## PART-A

##### 1.Create a Notebook to demonstrate NumPy Operations.

In [273]:
import numpy as np

##### 2.Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [274]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

##### 3.Create a new array of shape 3 with random numbers between 0 and 1.

In [275]:
np.random.rand(3)

array([0.28361182, 0.25305624, 0.55138613])

##### 4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
     
#####       Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [276]:
#Create the 2D array
arr = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("2D array:")
print(arr)
# Slice to get the first two rows
firstTwoRows = arr[:2]
print("First two rows:")
print(firstTwoRows)

# Slice to get the last two rows
lastTwoRows = arr[-2:]
print("Last two rows:")
print(lastTwoRows)

2D array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]
First two rows:
[[10 20 45]
 [30 12 16]]
Last two rows:
[[30 12 16]
 [42 17 56]]


##### 5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
     

In [277]:
arr1 = np.array([[1,8],[3,7]])
arr2 = np.array([[4,3],[5,9]])

# Stack the arrays vertically
verticalStack = np.vstack((arr1, arr2))
print("Vertical stack:")
print(verticalStack)

# Stack the arrays horizontally
horizontalStack = np.hstack((arr1, arr2))
print("Horizontal stack:")
print(horizontalStack)

# Split the vertical stack into smaller arrays
splitVertical = np.vsplit(verticalStack, 4)
print("Split vertically:")
print(splitVertical)

# Split the horizontal stack into smaller arrays
splitHorizontal = np.hsplit(horizontalStack, 4)
print("Split horizontally:")
print(splitHorizontal)


Vertical stack:
[[1 8]
 [3 7]
 [4 3]
 [5 9]]
Horizontal stack:
[[1 8 4 3]
 [3 7 5 9]]
Split vertically:
[array([[1, 8]]), array([[3, 7]]), array([[4, 3]]), array([[5, 9]])]
Split horizontally:
[array([[1],
       [3]]), array([[8],
       [7]]), array([[4],
       [5]]), array([[3],
       [9]])]


#####  6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
     
#####     Demonstrate the case when it is not possible to.
      
    

In [278]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

print("Shape of X matrix: ",X.shape)
print("Shape of Y matrix: ", Y.shape)

print("It is possible multiply X with Y, as the number of columns in matrix X is equal to the number of rows in matrix Y.")

result = np.dot(X, Y)

print("Result Matrix: ")
print(result)

# Demonstrate the case when it is not possible to.
print("When we try to multiply Y and X using np.dot(Y, X), matrix multiplication is not possible due to incompatible dimensions, and an error is raised.")


Shape of X matrix:  (3, 3)
Shape of Y matrix:  (3, 2)
It is possible multiply X with Y, as the number of columns in matrix X is equal to the number of rows in matrix Y.
Result Matrix: 
[[70 28]
 [70 30]
 [60 26]]
When we try to multiply Y and X using np.dot(Y, X), matrix multiplication is not possible due to incompatible dimensions, and an error is raised.


#####  7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
     
#####      Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).
      
     

In [279]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Find shape and number of dimensions of x
xShape = x.shape
xDimensions = x.ndim
print("Shape of x:", xShape)
print("Number of dimensions of x:", xDimensions)

# Reshape x to a (3, 1) matrix
xReshaped = x.reshape((3, 1))
print("Reshaped x:")
print(xReshaped)

# Reshape y to a (3, 1) matrix and determine the number of dimensions
yReshaped = y.reshape((3, 1))
yDimensions = yReshaped.ndim
print("Reshaped y:")
print(yReshaped)
print("No. of dimensions of y after reshape:", yDimensions)

Shape of x: (3,)
Number of dimensions of x: 1
Reshaped x:
[[ 2]
 [-1]
 [-8]]
Reshaped y:
[[ 3]
 [ 1]
 [-2]]
No. of dimensions of y after reshape: 2


##### 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [280]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

# Create a scalar value
b = 2

# subtraction using broadcasting
subtractionResult = A - b
print("Subtraction result:")
print(subtractionResult)

# multiplication using broadcasting
multiplicationResult = A * b
print("\nMultiplication result:")
print(multiplicationResult)


Subtraction result:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Multiplication result:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## PART-B

#####     Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. 
#####         1. 2x1+3x2-4x3=6, x1-4x2=8


In [281]:
x = np.array([[2, 3, -4], [1, -4, 0]])
y = np.array([6, 8])
#z = np.linalg.solve(x, y)

#####        2. 3y1-4y2+5y3=10, -y1+2y2-4y3=8

In [282]:
x = np.array([[3, -4, -5], [-1, 2, -4]])
y = np.array([10, 8])
#z = np.linalg.solve(x, y)

##### There is no solution for above equations, as the number of equations are not equal to number of variables.