In [18]:
import numpy as np
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [19]:

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [20]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [43]:
df_1=pd.read_csv('Lab2_dataset.csv')

In [44]:
df_1.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\nth...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\n( see a...   
2        3624   ham  Subject: neon retreat\nho ho ho , we ' re arou...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\nthis deal is to ...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [45]:
# Preprocessing

df_1['text'] = df_1['text'].astype(str)
df_1['text'] = df_1['text'].str.replace('[^a-zA-Z]', ' ')
df_1['text'] = df_1['text'].str.lower()

<ipython-input-45-f41c683b5138>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df_1['text'] = df_1['text'].str.replace('[^a-zA-Z]', ' ')


In [46]:
# Tokenization
df_1['tokens'] = df_1['text'].apply(word_tokenize)

In [47]:
# Stop Word Removal
stop_words = set(stopwords.words('english'))
df_1['filtered_tokens'] = df_1['tokens'].apply(lambda x: [token for token in x if token not in stop_words])


In [48]:
# Feature Extraction using Bag-of-Words
vectorizer = CountVectorizer()
X= vectorizer.fit_transform(df_1['filtered_tokens'].apply(' '.join)).toarray()

In [49]:
df_1.head()

Unnamed: 0 label                                               text  \
0         605   ham  subject  enron methanol   meter            thi...   
1        2349   ham  subject  hpl nom for january            see at...   
2        3624   ham  subject  neon retreat ho ho ho   we   re aroun...   
3        4685  spam  subject  photoshop   windows   office   cheap ...   
4        2030   ham  subject  re   indian springs this deal is to b...   

   label_num                                             tokens  \
0          0  [subject, enron, methanol, meter, this, is, a,...   
1          0  [subject, hpl, nom, for, january, see, attache...   
2          0  [subject, neon, retreat, ho, ho, ho, we, re, a...   
3          1  [subject, photoshop, windows, office, cheap, m...   
4          0  [subject, re, indian, springs, this, deal, is,...   

                                     filtered_tokens  
0  [subject, enron, methanol, meter, follow, note...  
1  [subject, hpl, nom, january, see, attached, fi...  
2  [subject, neon, retreat, ho, ho, ho, around, w...  
3  [subject, photoshop, windows, office, cheap, m...  
4  [subject, indian, springs, deal, book, teco, p...

In [50]:
df_1=df_1.drop(['Unnamed: 0'],axis=1)

In [51]:
df_1=df_1.drop(['tokens'],axis=1)

In [52]:
df_1=df_1.drop(['filtered_tokens'],axis=1)

In [53]:
df_1.head()

label                                               text  label_num
0   ham  subject  enron methanol   meter            thi...          0
1   ham  subject  hpl nom for january            see at...          0
2   ham  subject  neon retreat ho ho ho   we   re aroun...          0
3  spam  subject  photoshop   windows   office   cheap ...          1
4   ham  subject  re   indian springs this deal is to b...          0

In [54]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [55]:
df_1.shape

(5171, 3)

In [56]:
#x=df_1.drop(['label'],axis=1)

In [57]:
y=df_1['label']

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [60]:
from sklearn.naive_bayes import GaussianNB

In [61]:
# Create an instance of the Gaussian classifier
gaussian_clf = GaussianNB()

# Train the Gaussian classifier on the training data
gaussian_clf.fit(X_train, y_train)

GaussianNB()

In [62]:
from sklearn.naive_bayes import MultinomialNB

# Create an instance of the Multinomial classifier
multinomial_clf = MultinomialNB()

# Train the Multinomial classifier on the training data
multinomial_clf.fit(X_train, y_train)

MultinomialNB()

In [63]:
from sklearn.metrics import accuracy_score

# Predict using the trained models on the test data
y_pred_gaussian = gaussian_clf.predict(X_test)
y_pred_multinomial = multinomial_clf.predict(X_test)



In [64]:
# Calculate the accuracy of the models
accuracy_gaussian = accuracy_score(y_test, y_pred_gaussian)
accuracy_multinomial = accuracy_score(y_test, y_pred_multinomial)

# Print the accuracies
print("Gaussian Classifier Accuracy:", accuracy_gaussian)
print("Multinomial Classifier Accuracy:", accuracy_multinomial)

Gaussian Classifier Accuracy: 0.9565217391304348
Multinomial Classifier Accuracy: 0.9777777777777777


# Perfromance 

The Multinomial Naive Bayes CLassifier perfroms better than Gaussian CLassifier. with accuracy of 97.77%.

# Part-II

# Outlier By Mean

In [7]:
df_2=pd.read_csv('AB_NYC_2019.csv')

In [8]:
df_2.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

In [14]:
df_2.shape

(48895, 16)

In [10]:
# Calculate the mean and standard deviation of price per night
mean_price = df_2['price'].mean()
std_price = df_2['price'].std()



In [11]:
# Define the threshold as, for example, 3 standard deviations from the mean
threshold = 3 * std_price



In [15]:
# Remove outliers based on price per night using mean and threshold
df_2_new_mean = df_2[(df_2['price'] >= mean_price - threshold) & (df_2['price'] <= mean_price + threshold)]

In [16]:
df_2_new_mean.shape

(48507, 16)

# Outlier By Median

In [19]:
# Calculate the median and median absolute deviation (MAD) of price per night
median_price = df_2['price'].median()
mad_price = df_2['price'].mad()


In [20]:

# Define the threshold as, for example, 3 median absolute deviations
threshold = 3 * mad_price



In [21]:
# Remove outliers based on price per night using median and threshold
df_2_median = df_2[(df_2['price'] >= median_price - threshold) & (df_2['price'] <= median_price + threshold)]

In [22]:
df_2_median.shape

(46700, 16)

In [23]:
df_2_median.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

# Outlier By Percentile

In [25]:
lower_percentile = df_2['price'].quantile(0.05)
upper_percentile = df_2['price'].quantile(0.95)


In [26]:

# Remove outliers based on price per night using percentiles
df_clean_percentile = df_2[(df_2['price'] >= lower_percentile) & (df_2['price'] <= upper_percentile)]