LAB:1 AMANDEEP KAUR (8896062)

PART A:
1.Create a Notebook to demonstrate NumPy Operations.

In [1]:
import numpy as np
import plotly.express as px

2.Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
array_with_steps = np.arange(1, 21, 3) # (start,stop, step)
print("array_with_steps :", array_with_steps)

array_with_steps : [ 1  4  7 10 13 16 19]


3.Create a new array of shape 3 with random numbers between 0 and 1.

In [3]:
np.random.rand(3,1)

array([[0.90940766],
       [0.49338987],
       [0.24227052]])

4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [4]:
np2dArray = np.array([[10,20,45], [30,12,16], [42,17,56]])
slice1 = np2dArray[:2,]
print(f'First slice \n{slice1}')

print(f'Second slice \n{np2dArray[1:3, ]}')

First slice 
[[10 20 45]
 [30 12 16]]
Second slice 
[[30 12 16]
 [42 17 56]]


5 . Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [5]:
array1 = np.array([[10,11],[12,13]])
array2 = np.array([[14,15],[16,17]])

#stacking the elements vertically
verticalStacking = np.vstack([array1,array2])
print(verticalStacking)

#stacking the elements horizontally
horizontalStacking = np.hstack([array1,array2])
print(horizontalStacking)

#splitting the horizontal stack
splitHorizontalStack = np.array_split(horizontalStacking,2)
print(splitHorizontalStack)

##splitting the vertical stack
splitVerticalStack=np.array_split(verticalStacking,2)
print(splitVerticalStack)

[[10 11]
 [12 13]
 [14 15]
 [16 17]]
[[10 11 14 15]
 [12 13 16 17]]
[array([[10, 11, 14, 15]]), array([[12, 13, 16, 17]])]
[array([[10, 11],
       [12, 13]]), array([[14, 15],
       [16, 17]])]


6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? Demonstrate the case when it is not possible to.

In [6]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

print(X.shape)
print(Y.shape)

(3, 3)
(3, 2)


AnS:(3, 3) matrix can be multiplied by a (3, 2) matrix. The column number of first matrix should be equal to the row number of second matrix. Therefore, X . Y has a solution but Y . X has not a solution.

In [7]:
# (m, n) x (n, p) --> (m, p)

X @ Y

array([[70, 28],
       [70, 30],
       [60, 26]])

In [8]:
Y @ X

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1)

In [ ]:
x = np.array([2, -1, -8]) 
y = np.array([3, 1, -2])

In [ ]:
print(f'Shape of x : {x.shape}')
print(f'Number of dimensions in x : {x.ndim}')
print(f'Shape of y : {y.shape}')
print(f'Number of dimensions in y : {y.ndim}')

Shape of x : (3,)
Number of dimensions in x : 1
Shape of y : (3,)
Number of dimensions in y : 1


In [ ]:
x = np.reshape(x, (3, 1))
print(f'Shape of x : {x.shape}')
print(f'Number of dimensions in x : {x.ndim}')

y = np.reshape(y, (3,1))
print(f'Shape of y : {y.shape}')
print(f'Number of dimensions in y : {y.ndim}')

Shape of x : (3, 1)
Number of dimensions in x : 2
Shape of y : (3, 1)
Number of dimensions in y : 2


8.How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

The term broadcasting refers to how Numpy treats array with different shapes during arithmetic operations. Boradcasting works by automatically making changes to the dimensions of two arrays with mismatch shapes to match each other, so that various arthemetic operations could be perfomed between them.

Source - Numpy Docs

In [ ]:
# Consider a 3 x 3 matrix

mat_a = np.array([[10,11,12],[13,14,15],[16,17,18]])
b = 2 # Though b is defined as a scalar, numpy automatically consider it as a vector during array operations (vectorization)

# Illustrating the subtraction by broadcasting

mat_sub = mat_a - b
print("The matrix subtraction will happen element by element due to broadcasting and the result is: \n", mat_sub)

# Illustrate Multiplication by broadcasting

mat_mul = mat_a * b
print("The matrix multiplication will happen element by element due to broadcasting and the result is: \n", mat_mul)

The matrix subtraction will happen element by element due to broadcasting and the result is: 
 [[ 8  9 10]
 [11 12 13]
 [14 15 16]]
The matrix multiplication will happen element by element due to broadcasting and the result is: 
 [[20 22 24]
 [26 28 30]
 [32 34 36]]


9.Add Markdown text, with a headline, that provides a very brief overview of the graphs (e.g., one sentence for each).
Feel free to add additional Markdown elements (description/additional comments)

Brief Overview of the graphs
Bar graph
A graph representing categorical data with rectangular bars of varying heights.

In [ ]:
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig.show()

Scatter graph
A graph displaying individual data points as markers on a coordinate grid.

In [ ]:
data = px.data.iris()
fig = px.scatter(data, x="sepal_width", y="sepal_length", color="species")
fig.show()

Pie Chart:
A pie chart is a circular figure that depicts the percentage or proportion of data.

In [ ]:
df = px.data.tips()
fig = px.pie(df, values='tip', names='day')
fig.show()

Line Plot
A graph showing the trend of a variable over a continuous range of values.

In [ ]:
df = px.data.gapminder().query("continent=='Oceania'")
fig = px.line(df, x="year", y="lifeExp", color="country", title='Life Expectancy in Oceania')
fig.show()

Part B
1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions.
Defining the feature matrix for given set of solutions 2x1+3x2-4x3 = 6; x1-4x2+0x3 = 8

In [ ]:
# Defining the feature matrix for given set of solutions 2x1+3x2-4x3 = 6; x1-4x2+0x3 = 8

A = np.array([[2,3,-4],[1,-4,0]])

# Defining the constants matrix for given set of equations

B = np.array([6,8])

print("The shape of A matrix is: \n", A.shape)
print("The shape of B matrix is: \n", B.shape)

solution = np.linalg.solve(A, B)

The shape of A matrix is: 
 (2, 3)
The shape of B matrix is: 
 (2,)


LinAlgError: Last 2 dimensions of the array must be square

As we can see from the error, there should be one more equation to obtain square maxrix.

In [ ]:
#  3y1-4y2+5y3 = 10; -y1+2y2-4y3 = 8

P = np.array([[3,-4,5],[-1,2,-4]])

# Defining the constants matrix for given set of equations

Q = np.array([10,8])

print("The shape of P matrix is: \n", P.shape)
print("The shape of Q matrix is: \n", Q.shape)

The shape of P matrix is: 
 (2, 3)
The shape of Q matrix is: 
 (2,)


Checking the singularity of P matrix
This case is similar to the previous case.
det_X = np.linalg.det(P)
To find the singularity of matrix P, we need to ensure the determinant of matrix P is a non-zero value.
However, the shape of P matrix is 2 x 3, which is a non-square matrix. Hence, we can't calculate the determinant.
Without finding the determinant, we can't apply inverse operation to matrix P and we don't have the idea whether we have no solutions, finite solutions, or infinite solutions.
To find the solution matrix [y1, y2, y3], we need to find the inverse of P and multiply with matrix Q.
As we can't inverse the matrix P, it is impossible to find the solution for [y1, y2, y3]
If we could have find determinant and ensure it is non-zero value, we can apply np.linalg.solve(P,Q) to find the solution matrix.
This is an alternate method to find the solution matrix using numpy operations.