#### PRAMOD KUNJUKUNJU SAJI
#### 8856432
#### Lab 1

#### **Part A**
##### 1. Create a Notebook to demonstrate NumPy Operations.

In [32]:
import numpy as np

##### 2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [33]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

##### 3. Create a new array of shape 3 with random numbers between 0 and 1.

In [34]:
np.random.rand(3)

array([0.29114348, 0.01670939, 0.33501562])

##### 4. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
##### Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [35]:
twoDArray = np.array([[10,20,45], [30,12,16], [42,17,56]])
print('First 2 rows: ')
print(twoDArray[:2])
print('Last 2 rows: ')
print(twoDArray[-2:])

First 2 rows: 
[[10 20 45]
 [30 12 16]]
Last 2 rows: 
[[30 12 16]
 [42 17 56]]


#####  5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [36]:
# Inititalizing two 2x2 arrays
firstArray = np.array([[90, 80], [30, 40]])
secondArray = np.array([[10, 20], [60, 50]])

# Stacking the arrays vertically
verticalStack = np.vstack((firstArray, secondArray))
print('Vertically Stacked Array: ')
print(verticalStack)

# Stacking the arrays horizontally
horizontalStack = np.hstack((secondArray, firstArray))
print('Horizontally Stacked Array: ')
print(horizontalStack)

# Splitting vertical array
verticalSplitArray = np.vsplit(verticalStack, 2)
print('Split vertically: ')
print(verticalSplitArray)

# Splitting horizontally array
horizontalSplitArray = np.hsplit(horizontalStack, 2)
print('Split horizontally: ')
print(horizontalSplitArray)

Vertically Stacked Array: 
[[90 80]
 [30 40]
 [10 20]
 [60 50]]
Horizontally Stacked Array: 
[[10 20 90 80]
 [60 50 30 40]]
Split vertically: 
[array([[90, 80],
       [30, 40]]), array([[10, 20],
       [60, 50]])]
Split horizontally: 
[array([[10, 20],
       [60, 50]]), array([[90, 80],
       [30, 40]])]


##### 6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
#####     Demonstrate the case when it is not possible to.

In [37]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

result1 = np.matmul(X, Y)
print('X * Y = ', result1)

print('Y * X is not possible as shapes are not in the right order')

X * Y =  [[70 28]
 [70 30]
 [60 26]]
Y * X is not possible as shapes are not in the right order


##### 7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
##### Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).
      

In [38]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print('Shape of x: ', x.shape)
print('Number of dimensions of x: ', x.ndim)

xReshaped = x.reshape((3, 1))
yReshaped = y.reshape((3, 1))

print('Reshaped x: ')
print(xReshaped)
print('Number of dimensions of reshaped x: ', xReshaped.ndim)

print("Reshaped y: ")
print(yReshaped)
print('Number of dimensions of reshaped y: ', yReshaped.ndim)

Shape of x:  (3,)
Number of dimensions of x:  1
Reshaped x: 
[[ 2]
 [-1]
 [-8]]
Number of dimensions of reshaped x:  2
Reshaped y: 
[[ 3]
 [ 1]
 [-2]]
Number of dimensions of reshaped y:  2


##### 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [39]:
# Creating a 3x3 matrix
matrix = np.array([[20, 70, 50],
                   [90, 10, 60],
                   [30, 80, 40]])

# Subtraction
subtractedMatrix = matrix - 10
print("Subtracted Matrix: ", subtractedMatrix)

# Multiplication
multipliedMatrix = matrix * 2
print("Multiplied Matrix: ", multipliedMatrix)

Subtracted Matrix:  [[10 60 40]
 [80  0 50]
 [20 70 30]]
Multiplied Matrix:  [[ 40 140 100]
 [180  20 120]
 [ 60 160  80]]


 ##### 9. Add Markdown text, with a headline, that provides a very brief overview of the graphs (eg., one sentence for each).
 ##### Feel free to add additional Markdown elements (description/additional comments)
        

##### 1. **Line graph** - representation of data points connected by straight lines to show the relationship between variables over time or other continuous intervals.

##### 2. **Bar chart** - representation of categorical data using rectangular bars of different lengths to compare and display values or frequencies

##### 3. **Histogram** - displays the distribution of numerical data using a series of contiguous bars, where the height of each bar represents the frequency or count of data within a specific range or bin

##### 4. **Scatter plot** - representation of data points in which individual observations are plotted as dots on a two-dimensional coordinate system, allowing for the visualization of the relationship or correlation between two variables

##### 5. **Box plot** - representation of the distribution of numerical data through quartiles, outliers, and the range of the data, displayed as a rectangular box with whiskers


#### **Part B**

#####     1. Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. 
##### 1. 2x1+3x2-4x3=6,x1-4x2=8
	
##### 2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [40]:
# Solving "2x1+3x2-4x3=6,x1-4x2=8"
X = np.array([[2, 3, -4], [1, -4, 0]])
y = np.array([6, 8])
z = np.linalg.solve(X, y)

LinAlgError: Last 2 dimensions of the array must be square

As the error states, **"Last 2 dimensions of the array must be square"**

In [ ]:
# Solving "3y1-4y2+5y3=10,-y1+2y2-4y3=8"
X = np.array([[3, -4, -5], [-1, 2, -4]])
y = np.array([10, 8])
z = np.linalg.solve(X, y)

LinAlgError: Last 2 dimensions of the array must be square

As the error states, **"Last 2 dimensions of the array must be square"**