## Lab:- 1 Dhrushil Patel(8862870)

### Part:- A

#### 1. Create a Notebook to demonstrate NumPy Operations.

In [14]:
# importing the required libraries
import numpy as np

####  2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [15]:
# creating an array using arange function:
arr1 = np.arange(1, 20, 3)
print(arr1)

[ 1  4  7 10 13 16 19]


#### 3. Create a new array of shape 3 with random numbers between 0 and 1.

In [16]:
# creating an array using random function:
arr2 = np.random.rand(3)
print(arr2)

[0.36855877 0.59335918 0.09144022]


#### 4. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
     
#### Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [17]:
# creating an array using array function:
arr3 = np.array([[10,20,45], [30,12,16], [42,17,56]])
print(arr3)

# print dimention of the array
print("Dimenstions of the array: ", arr3.ndim)

[[10 20 45]
 [30 12 16]
 [42 17 56]]
Dimenstions of the array:  2


In [18]:
# Slice the 2D array to get the first two rows.
print("First two rows:\n ", arr3[:2])

#slice the 2D array to get the last two rows.
print("\nLast two rows:\n ", arr3[1:])

First two rows:
  [[10 20 45]
 [30 12 16]]

Last two rows:
  [[30 12 16]
 [42 17 56]]


#### 5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [19]:
# Creating a 2x2 arrays:
arr4 = np.array([[21, 22], [23, 24]])
arr5 = np.array([[25, 26], [27, 28]])

# Vertically stacking the arrays:
print("Vertical stacking:\n", np.vstack((arr4, arr5)))

# Horizontally stacking the arrays:
print("\n Horizontal stacking:\n", np.hstack((arr4, arr5)))

# Splititing the vertical array:
print("\n Splitting vertically:\n", np.vsplit(arr4, 2))

# Splitting the horizontal array:
print("\n Splitting horizontally:\n", np.hsplit(arr4, 2))



Vertical stacking:
 [[21 22]
 [23 24]
 [25 26]
 [27 28]]

 Horizontal stacking:
 [[21 22 25 26]
 [23 24 27 28]]

 Splitting vertically:
 [array([[21, 22]]), array([[23, 24]])]

 Splitting horizontally:
 [array([[21],
       [23]]), array([[22],
       [24]])]


#### 6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 

In [20]:
# Creating the two matrices:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11], [13, 14], [16, 17]])

# Print the Shape to these matrices:
print("Shape of matrix A: ", A.shape)
print("Shape of matrix B: ", B.shape)

# Multiplying these two matrices:
print("\n Multiplication of two matrices:\n", np.dot(A, B))

# print the shape of final product:
print("\n Shape of the final product: ", np.dot(A, B).shape)


Shape of matrix A:  (3, 3)
Shape of matrix B:  (3, 2)

 Multiplication of two matrices:
 [[ 84  90]
 [201 216]
 [318 342]]

 Shape of the final product:  (3, 2)


So as per the upper out put we can say that we can do multilication with A and B matrix because in both of them have 3 row and 3 coloums, however in secound view we cany multipley B with A because the coloume and raw values are not matches with other.

#### 7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
     
#### Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [21]:
# Creating the two arrays x and y:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Shape of the vector x and y:
print("Shape of vector x: ", x.shape)
print("Shape of vector y: ", y.shape)

# Dimensions of vector x and y:
print("\nDimensions of vector x: ", x.ndim)
print("Dimensions of vector y: ", y.ndim)

# Reshaping x and y to a matrix of size (3,1):
x = x.reshape(3, 1)
y = y.reshape(3, 1)

# Printing out x and y after reshaping:
print("\nx after reshaping:\n", x)
print("y after reshaping:\n", y)

# Printing out the shape of x and y after reshaping:
print("\nShape of x after reshaping: ", x.shape)
print("Shape of y after reshaping: ", y.shape)

# Printing out the dimensions of both x and y after reshaping:
print("\nDimensions of x after reshaping: ", x.ndim)
print("Dimensions of y after reshaping: ", y.ndim)


Shape of vector x:  (3,)
Shape of vector y:  (3,)

Dimensions of vector x:  1
Dimensions of vector y:  1

x after reshaping:
 [[ 2]
 [-1]
 [-8]]
y after reshaping:
 [[ 3]
 [ 1]
 [-2]]

Shape of x after reshaping:  (3, 1)
Shape of y after reshaping:  (3, 1)

Dimensions of x after reshaping:  2
Dimensions of y after reshaping:  2


####  8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

The phrase "broadcasting" refers to how Numpy handles exhibits with different forms when doing math operations. Numpy vectorizes the illustrated scenario by iterating over the lattice component by component whenever any math operation is done to a grid.

In [22]:
# Demonstrating arithematic operations with a 3 x 3 matrix
# Creating a 3 x 3 matrix:
A = np.array([[21, 22, 23], [24, 25, 26], [27, 28, 29]])
B = 10

# Illustrating the subtraction by broadcasting:
print("Subtraction by broadcasting:\n", A - B)

# Illustrating the multiplication by broadcasting:
print("\nMultiplication by broadcasting:\n", A * B)

Subtraction by broadcasting:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplication by broadcasting:
 [[210 220 230]
 [240 250 260]
 [270 280 290]]


### Part:- B

#### 1. Solve the following two system of linear equations using matrices (find the values of x1 and x2) and 
#### determine the number of solutions using the functions. 

#### 1.2x1+3x2-4x3=6,x1-4x2=8
#### 2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [23]:
# Solving Eq 1:
# Creating the matrices:
A = np.array([[1.2, 3, -4], [1, -4, 0]])
B = np.array([6, 8])

# Solving the system of linear equation:
print("Solution of the system of linear equation:\n", np.linalg.solve(A, B))



LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
print("Shape of EQ-A: ", A.shape)

Shape of EQ-A:  (2, 3)


The error message "LinAlgError: Last 2 Elements of the Exhibit Should Be Square" reveals a problem with the code. The network eq1 is unquestionably not a square lattice, hence the number of lines isn't equal to the number of segments, which causes an error when using the linalg.solve feature.

The network "EQ-A" in our instance is not square since it consists of two lines and three sections. We are unable to compute its determinant since the grid isn't square. Whether a lattice is solitary or non-particular must be determined by the determinant.

In [24]:
# Solving Eq 2:
# Creating the matrices:
A = np.array([[3, -4, 5], [-1, 2, -4]])
B = np.array([10, 8])

# Solving the system of linear equation:
print("Solution of the system of linear equation:\n", np.linalg.solve(A, B))

LinAlgError: Last 2 dimensions of the array must be square

In [25]:
print("Shape of EQ-2: ", A.shape)

Shape of EQ-2:  (2, 3)


Due to a similar rationale, an error also occurs in this configuration. The fact that the structure "EQ-2" includes 2 lines and 3 sections further demonstrates that it is not a square lattice. Therefore, this condition is intractable, and we are unable to determine how many possible solutions there are.