## Lab 1 - Abijith Suresh km - 8899968

### Part A

1 . Create a Notebook to demonstrate NumPy Operations.

In [32]:
# importing the packages

import numpy as np

2 . Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [33]:
array = np.arange(1,20,3) 
print(array)

[ 1  4  7 10 13 16 19]


3 . Create a new array of shape 3 with random numbers between 0 and 1.

In [34]:
np.random.rand(3)

array([0.2284635 , 0.42188826, 0.98105328])

4 . Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
    
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [35]:
array = np.array([[10,20,45], [30,12,16], [42,17,56]]) # 2D array created

# Slicing first two row
sF2R =array[0:2]
print(sF2R)

# Slicing last two row
sL2R =array[:0:-1]
print(sL2R)

[[10 20 45]
 [30 12 16]]
[[42 17 56]
 [30 12 16]]


5 . Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [36]:
array1 = np.array([[10,11],[12,13]])
array2 = np.array([[14,15],[16,17]])

#stacking the elements vertically
verticalStacking = np.vstack([array1,array2])
print(verticalStacking)

#stacking the elements horizontally
horizontalStacking = np.hstack([array1,array2])
print(horizontalStacking)

#splitting the horizontal stack
splitHorizontalStack = np.array_split(horizontalStacking,2)
print(splitHorizontalStack)

##splitting the vertical stack
splitVerticalStack=np.array_split(verticalStacking,2)
print(splitVerticalStack)

[[10 11]
 [12 13]
 [14 15]
 [16 17]]
[[10 11 14 15]
 [12 13 16 17]]
[array([[10, 11, 14, 15]]), array([[12, 13, 16, 17]])]
[array([[10, 11],
       [12, 13]]), array([[14, 15],
       [16, 17]])]


6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
         
 Demonstrate the case when it is not possible to

In [37]:
matrices_X = np.array ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
matrices_Y = np.array ([[4, 2], [6, 2], [4, 2]])

Z = matrices_X @ matrices_Y 
print(Z)

[[70 28]
 [70 30]
 [60 26]]


7 . Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
         
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [38]:
arrayX = np.array([2, -1, -8])
arrayY = np.array([3,1,-2])

print("Shape of arrayX is :", arrayX.shape)
print("Shape of arrayY is :", arrayY.shape)
print("Number of dimension of vector is :", arrayX.ndim)

# Reshape the vector X to (3,1)
arrayXReshaped = arrayX.reshape(3,1)
print("The reshaped matrix ", arrayXReshaped)

# Number of dimensions after reshaping y to a matrix of (3,1)
arrayYReshaped = arrayY.reshape(3,1)
print("The dimensions of y_reshaped is:", arrayYReshaped.ndim)


Shape of arrayX is : (3,)
Shape of arrayY is : (3,)
Number of dimension of vector is : 1
The reshaped matrix  [[ 2]
 [-1]
 [-8]]
The dimensions of y_reshaped is: 2


8 . How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

Broadcasting : 

Broadcasting is a concept in array manipulation that allows arrays of different shapes to be used together in operations. When performing operations on arrays with different shapes, broadcasting ensures that the arrays are compatible by adjusting their shapes to match.

In [39]:
A = np.array ([[2, 3, 4],
               [5, 5, 6],
               [7, 8, 9]])
B = 2

# Substraction of matrix

Substraction = A-B
print(Substraction)

# Multiplication of matrix

multiplication = A*B
print(multiplication)


[[0 1 2]
 [3 3 4]
 [5 6 7]]
[[ 4  6  8]
 [10 10 12]
 [14 16 18]]


### Part B

1 . Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the 
    functions. 

1 . 2x1+3x2-4x3=6,x1-4x2=8


In [44]:

# Define the coefficients matrix A
A = np.array([[2, 3, -4], [1, -4, 0]])

# Define the constants vector B
B = np.array([6, 8])

print(" shape of a matrix is: \n", A.shape)

print("shape of b matrix is: \n", B.shape)

# Solve the system of equations

X = np.linalg.solve(A, B)

# finding the shape

print(X)

 shape of a matrix is: 
 (2, 3)
shape of b matrix is: 
 (2,)


Error will be thrown this is likely because the matrix is not invertible, meaning it is singular. In order to use np.linalg.solve() function to solve the linear equations, the coefficient matrix X must be non-singular.

2 . 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [46]:
X = np.array([[3,-4,5],[-1,2,-4]])

# Constants matrix for given set of equations

Y = np.array([10,8])

#finding the shape
print(" shape of a matrix is: \n", X.shape)
print(" shape of a matrix is: \n", Y.shape)

Z = np.linalg.solve(X, Y)
#linalg it allows you to solve problems related to vectors, matrices, and linear equations
print(Z)

 shape of a matrix is: 
 (2, 3)
 shape of a matrix is: 
 (2,)


Error will be thrown this is likely because the matrix is not invertible, meaning it is singular. In order to use np.linalg.solve() function to solve the linear equations, the coefficient matrix must be non-singular.