# **Practical Lab-1 Dwarakanath Chandra (8856840)**

# **Basic Numpy Operations**

## **Part-A**

#### **1. Create a Notebook to demonstrate NumPy Operations.**

lab1.ipynb in the subfolder 8856840 inside student_submissions is the jupyter notebook created to demonstrate Numpy Operations.

In [21]:
# Importing numpy package as np

import numpy as np

#### **2. Create an array that starts from the integer 1, ends at 20, incremented by 3.**

In [22]:
np.arange(start = 1, stop = 20, step = 3) # Create an array starts with 1 ends at 20 with a difference of 3 between successive elements

array([ 1,  4,  7, 10, 13, 16, 19])

#### **3. Create a new array of shape 3 with random numbers between 0 and 1.**

In [23]:
np.random.rand(3) # Generates 3 random values between 0 and 1

array([0.28520257, 0.21662104, 0.93135006])

#### **4. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:**
     
##### **Slice the 2D array to get the first two rows**
##### **Slice the 2D array to get the last two rows**

In [24]:
arr1 = np.array([[10,20,45], [30,12,16], [42,17,56]]) # Creating a 3 X 3 matrix in 2 dimensions.
print(arr1)
print("The dimensions of the arr1: ", arr1.ndim) # ndim will give dimensions of a matrix

[[10 20 45]
 [30 12 16]
 [42 17 56]]
The dimensions of the arr1:  2


In [25]:
# 4.a) Slicing the 2D-array arr1 to extract first 2 rows

arr1[:2,:] # Slices the rows with index 0 and 1 and excludes row with index 2 and selects all column elements

array([[10, 20, 45],
       [30, 12, 16]])

In [26]:
# 4.b) Slicing the 2D-array arr1 to extract last 2 rows

arr1[-2:,:] # Slices the last 2 rows of the matrix irrespective of number of rows and also selects all column elements.

array([[30, 12, 16],
       [42, 17, 56]])

#### **5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.**

In [27]:
arr_1 = np.array([[11,12],[13,14]])
arr_2 = np.array([[15,16],[17,18]])

# Stacking the arr_1 & arr_2 horizontally

h_array = np.hstack([arr_1,arr_2])
print("The horizontally stacked array is : \n", h_array)
# Stacking the arr_1 & arr_2 vertically
v_array = np.vstack([arr_1,arr_2])
print("The vertically stacked array is : \n", v_array)

# Splitting the 2 x 4 horizontally stacked array into 4 smaller arrays along the columns

split_h_array = np.array_split(h_array, indices_or_sections = 4, axis = 1) # Similar to np.vsplit(h_array, 4)
print("The splitted arrays generated from h_array splitting are: \n", split_h_array)

# Splitting the 4 x 2 horizontally stacked array into 4 smaller arrays along the rows

split_v_array = np.array_split(v_array, indices_or_sections=4, axis = 0) # Similar to np.hsplit(v_array, 4)
print("The splitted arrays generated from v_array splitting are: \n", split_v_array)

The horizontally stacked array is : 
 [[11 12 15 16]
 [13 14 17 18]]
The vertically stacked array is : 
 [[11 12]
 [13 14]
 [15 16]
 [17 18]]
The splitted arrays generated from h_array splitting are: 
 [array([[11],
       [13]]), array([[12],
       [14]]), array([[15],
       [17]]), array([[16],
       [18]])]
The splitted arrays generated from v_array splitting are: 
 [array([[11, 12]]), array([[13, 14]]), array([[15, 16]]), array([[17, 18]])]


#### **6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? Demonstrate the case when it is not possible to.**

In [28]:
# Creating the X and Y matrices

X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])
print("The shape of X matrix is: \n", X.shape)
print("The shape of Y matrix is: \n", Y.shape)

# Multiply X and Y matrices

# As the number of columns in X matrix is equal to the number of rows in Y matrix, we can multiply X with Y

Z = np.matmul(X, Y) # we can achieve the same with Z = X @ Y  or Z = X.dot(Y)

print("The product of X and Y is a 3 X 2 matrix: \n", Z)

print("However, we can't multiple Y with X because there are 2 columns in Y matrix and 3 rows in the X matrix.\nAs the count of columns in Y is not matching with count of rows in X, multiplication of Y with X matrix will not be possible in matrix algebra.\nHence, np.matmul(Y, X) is not possible")

The shape of X matrix is: 
 (3, 3)
The shape of Y matrix is: 
 (3, 2)
The product of X and Y is a 3 X 2 matrix: 
 [[70 28]
 [70 30]
 [60 26]]
However, we can't multiple Y with X because there are 2 columns in Y matrix and 3 rows in the X matrix.
As the count of columns in Y is not matching with count of rows in X, multiplication of Y with X matrix will not be possible in matrix algebra.
Hence, np.matmul(Y, X) is not possible


#### **7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x**
     
#### **Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).**

In [29]:
# Creating the arrays X and Y

x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Finding the shape and dimension of x
print("The shape of x is: \n", x.shape)
print("The dimension of matrix x is: \n", x.ndim)

# Reshaping the vector x and y to a matrix of size (3,1)
x_reshaped = x.reshape(3,1)
y_reshaped = y.reshape(3,1)
print("The reshaped matrix x is: \n", x_reshaped)
print("The reshaped matrix y is: \n", y_reshaped)

# Finding the number of dimensions of y_reshaped
print("The dimensions of y_reshaped is: \n", y_reshaped.ndim)

The shape of x is: 
 (3,)
The dimension of matrix x is: 
 1
The reshaped matrix x is: 
 [[ 2]
 [-1]
 [-8]]
The reshaped matrix y is: 
 [[ 3]
 [ 1]
 [-2]]
The dimensions of y_reshaped is: 
 2


#### **8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.**

#### **Broadcasting:**
##### When any arithmetic operation is applied on a matrix, numpy vectorizes the array operation by looping through the matrix element by element. This process is called as broadcasting.

In [30]:
# Consider a 3 x 3 matrix

mat_a = np.array([[10,11,12],[13,14,15],[16,17,18]])
b = 2 # Though b is defined as a scalar, numpy automatically consider it as a vector during array operations (vectorization)

# Illustrating the subtraction by broadcasting

mat_sub = mat_a - b
print("The matrix subtraction will happen element by element due to broadcasting and the result is: \n", mat_sub)

# Illustrate Multiplication by broadcasting

mat_mul = mat_a * b
print("The matrix multiplication will happen element by element due to broadcasting and the result is: \n", mat_mul)

The matrix subtraction will happen element by element due to broadcasting and the result is: 
 [[ 8  9 10]
 [11 12 13]
 [14 15 16]]
The matrix multiplication will happen element by element due to broadcasting and the result is: 
 [[20 22 24]
 [26 28 30]
 [32 34 36]]


## **Part-B**

#### **1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions.**
##### **2x1+3x2-4x3=6, x1-4x2=8**
##### **3y1-4y2+5y3=10,-y1+2y2-4y3=8**

### **Part-B 1A Solution:**

In [31]:
# Defining the feature matrix for given set of solutions 2x1+3x2-4x3 = 6; x1-4x2+0x3 = 8

A = np.array([[2,3,-4],[1,-4,0]])

# Defining the constants matrix for given set of equations

B = np.array([6,8])

print("The shape of A matrix is: \n", A.shape)
print("The shape of B matrix is: \n", B.shape)


The shape of A matrix is: 
 (2, 3)
The shape of B matrix is: 
 (2,)


##### **Checking the singularity of A matrix**

##### det_X = np.linalg.det(A)

##### To find the singularity of matrix A, we need to ensure the determinant of matrix A is a non-zero value.
##### However, the shape of A matrix is 2 x 3, which is a non-square matrix. Hence, we can't calculate the determinant.
##### Without finding the determinant, we can't apply inverse operation to matrix A and we don't have the idea whether we have no solutions, finite solutions, or infinite solutions.
##### To find the solution matrix [x1, x2, x3], we need to find the inverse of A and multiply with matrix B.
##### As we can't inverse the matrix A, it is impossible to find the solution for [x1, x2, x3]
##### If we could have find determinant and ensure it is non-zero value, we can apply np.linalg.solve(A, B) to find the solution matrix.
##### This is an alternate method to find the solution matrix using numpy operations.


### **Part-B 1B Solution:**

In [32]:
# Defining the feature matrix for given set of solutions 3y1-4y2+5y3 = 10; -y1+2y2-4y3 = 8

P = np.array([[3,-4,5],[-1,2,-4]])

# Defining the constants matrix for given set of equations

Q = np.array([10,8])

print("The shape of P matrix is: \n", P.shape)
print("The shape of Q matrix is: \n", Q.shape)

The shape of P matrix is: 
 (2, 3)
The shape of Q matrix is: 
 (2,)


##### **Checking the singularity of P matrix**

##### This case is similar to the previous case.

##### det_X = np.linalg.det(P)

##### To find the singularity of matrix P, we need to ensure the determinant of matrix P is a non-zero value.
##### However, the shape of P matrix is 2 x 3, which is a non-square matrix. Hence, we can't calculate the determinant.
##### Without finding the determinant, we can't apply inverse operation to matrix P and we don't have the idea whether we have no solutions, finite solutions, or infinite solutions.
##### To find the solution matrix [y1, y2, y3], we need to find the inverse of P and multiply with matrix Q.
##### As we can't inverse the matrix P, it is impossible to find the solution for [y1, y2, y3]
##### If we could have find determinant and ensure it is non-zero value, we can apply np.linalg.solve(P,Q) to find the solution matrix.
##### This is an alternate method to find the solution matrix using numpy operations.
