Lab 1 - Ashkar kammala puthenpura abdulkhadar - 8901587

Part A

1 . Create a Notebook to demonstrate NumPy Operations.

In [58]:
import numpy as np # import numpy 


2 . Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [59]:
arr1 = np.arange(1,20,3) 
print(arr1)

[ 1  4  7 10 13 16 19]


3. Create a new array of shape 3 with random numbers between 0 and 1

In [60]:


arr2= np.random.rand(3,1)
arr2

array([[0.10728251],
       [0.80244088],
       [0.73962651]])

4 . Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [61]:
arr3 = np.array([[10,20,45], [30,12,16], [42,17,56]]) # two dimensional array asskgned to arr3
arr2_first =arr3[0:2]#Slicing first two row
print(arr2_first)
arr2_last =arr3[:0:-1]# Slicing last two row
print(arr2_last)

[[10 20 45]
 [30 12 16]]
[[42 17 56]
 [30 12 16]]


5 . Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays

In [62]:
arr4 = np.array([[1,2],[2,3]])
arr5 = np.array([[4,5],[6,7]])

#stacking the elements vertically
v_stack = np.vstack((arr4,arr5))
print(v_stack)

#stacking the elements horizontally
h_stack = np.hstack((arr4,arr5))
print(h_stack)

#splitting the horizontal stack
split_h_stack = np.array_split(h_stack,2)
print(split_h_stack)

##splitting the vertical stack
split_v_stack=np.array_split(v_stack,2)
print(split_v_stack)

[[1 2]
 [2 3]
 [4 5]
 [6 7]]
[[1 2 4 5]
 [2 3 6 7]]
[array([[1, 2, 4, 5]]), array([[2, 3, 6, 7]])]
[array([[1, 2],
       [2, 3]]), array([[4, 5],
       [6, 7]])]


6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?
Demonstrate the case when it is not possible to.



In [63]:
x = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
y = np.array([[4, 2], [6, 2], [4, 2]])

print(x.shape)
print(y.shape)



(3, 3)
(3, 2)


In [64]:
x@y  # x is possible to multiple by y becuase of x first column number is equal to y's first raw number 

array([[70, 28],
       [70, 30],
       [60, 26]])

In [65]:
y@x

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

y*x is not possible becuase y's first coloumn number is not equal to x's first raw number 

7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x. Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).


In [ ]:
x = np.array([2, -1, -8]) 
y = np.array([3, 1, -2])
print('Shape of x:' , x.shape)
print('Number of dimensions in x ',x.ndim)
print('Shape of y : ',y.shape)
print('Number of dimensions in y :', y.ndim)
x = np.reshape(x, (3, 1))
print('Shape of x :', x.shape)
print('Number of dimensions in x :', x.ndim)

y = np.reshape(y, (3,1))
print('Shape of y :',y.shape)
print('Number of dimensions in y : ',y.ndim)

Shape of x: (3,)
Number of dimensions in x  1
Shape of y :  (3,)
Number of dimensions in y : 1
Shape of x : (3, 1)
Number of dimensions in x : 2
Shape of y : (3, 1)
Number of dimensions in y :  2


8 . How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

Broadcasting is a concept in array manipulation that allows arrays of different shapes to be used together in operations. When performing operations on arrays with different shapes, broadcasting ensures that the arrays are compatible by adjusting their shapes to match.

In [ ]:
A = np.array ([[2, 3, 4],
               [5, 5, 6],
               [7, 8, 9]])
B = 2
# Substraction of matrix
Substraction = A-B
print(Substraction)
# Multiplication of matrix
multiplication = A*B
print(multiplication)

[[0 1 2]
 [3 3 4]
 [5 6 7]]
[[ 4  6  8]
 [10 10 12]
 [14 16 18]]


Part B

1 . Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions.

1.1 . 2x1+3x2-4x3=6,x1-4x2=8

In [ ]:
arr1 = np.array([[2, 3, -4], [1, -4, 0]])#coefficient of matrix
solution = np.array([6, 8])#constant vector!!!
print(" shape of a matrix is: \n", arr1.shape)
print("shape of b matrix is: \n", solution.shape)
# Solve the system of equations
X = np.linalg.solve(arr1,solution)
# finding the shape
print(X)

 shape of a matrix is: 
 (2, 3)
shape of b matrix is: 
 (2,)


LinAlgError: Last 2 dimensions of the array must be square

 The matrix is not invertible,so it is singular. when we use np.linalg.solve() function to solve the linear equations, the coefficient matrix X must be non-singular.if it not,  then the error will come up like this,

2 . 3y1-4y2+5y3=10,   -y1+2y2-4y3=8

In [ ]:
arr1 = np.array([[3, -4, 5], [-1, 2, -4]])#coefficient of matrix
solution = np.array([10, 8])#constant vector!!!
print(" shape of a matrix is: \n", arr1.shape)
print("shape of b matrix is: \n", solution.shape)
# Solve the system of equations
X = np.linalg.solve(arr1,solution)
# finding the shape
print(X)

 shape of a matrix is: 
 (2, 3)
shape of b matrix is: 
 (2,)


LinAlgError: Last 2 dimensions of the array must be square

the same issue that appered in the above question, it is not invertabile ......