## NAME:AYODELE JAMES
SUDENT ID:8900611

Create a Notebook to demonstrate NumPy Operations

In [29]:
import numpy as np 

#question2:Create an array that starts from the integer 1, ends at 20, incremented by 3

In [30]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

#3:.Create a new array of shape 3 with random numbers between 0 and 1.

In [31]:
array2 = np.random.random((3))
print("Array 2:", array2)

Array 2: [0.1663005  0.37703223 0.46028673]


#question 4: Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows

In [32]:
Two_D_array = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("2-D array:\n {}".format(Two_D_array))

# Slice the 2D array to get the first two rows
First_2_rows =Two_D_array[:2, :]
print("First two rows:\n {}".format(First_2_rows))    

# Slice the 2D array to get the last two rows
Last_2_rows = Two_D_array[1:, :]
print("Last two rows:\n", Last_2_rows)

2-D array:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]
First two rows:
 [[10 20 45]
 [30 12 16]]
Last two rows:
 [[30 12 16]
 [42 17 56]]


#question 5: Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [33]:
# Create input array 1 & 2
in_arr1 = np.array([[7, 2], [9, 4]])
print ("1st Input array : \n", in_arr1) 
in_arr2 = np.array([[5, 6], [18, 8]])
print ("2nd Input array : \n", in_arr2) 
# Stack the elements vertically
Vertical_stack = np.vstack((in_arr1, in_arr2))
print("Vertical Stack:",Vertical_stack)

# Stack the elements horizontally
Horizontal_stack = np.hstack((in_arr1, in_arr2))
print("Horizontal Stack:",Horizontal_stack)

# Split the arrays into smaller arrays
split_in_arr1 = np.split(in_arr1, 2)
split_in_arr2 = np.split(in_arr2, 2)
print("Split Array 1:", split_in_arr1)
print("Split Array 2:",split_in_arr2 )

1st Input array : 
 [[7 2]
 [9 4]]
2nd Input array : 
 [[ 5  6]
 [18  8]]
Vertical Stack: [[ 7  2]
 [ 9  4]
 [ 5  6]
 [18  8]]
Horizontal Stack: [[ 7  2  5  6]
 [ 9  4 18  8]]
Split Array 1: [array([[7, 2]]), array([[9, 4]])]
Split Array 2: [array([[5, 6]]), array([[18,  8]])]


question 6:.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?

In [34]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

result = np.dot(X, Y)

print(result)

[[70 28]
 [70 30]
 [60 26]]


This is the result of multiplying X and Y.

Now, if we try to multiply matrices with incompatible shapes, we will get an error. For example,X=[1, 2, 3]and Z=[4, 5, 6]

In [35]:
Z = np.array([[1, 2, 3], [4, 5, 6]])
result = np.dot(X, Z)  # This will raise a ValueError

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

#This is because the number of columns in the first matrix (3) doesn't match the number of rows in the second matrix (2).

#question 7:Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
         
 Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).
          

In [ ]:
# create array x
x = np.array([2, -1, -8])

# create array y
y = np.array([3, 1, -2])

# find the shape of x
print(x.shape)  # output: (3,)

# find the number of dimensions of x
print(x.ndim)  # output: 1

(3,)
1


In [ ]:
# reshape x to a matrix of size (3, 1)
x_matrix = x.reshape(3, 1)

# find the number of dimensions of x_matrix
print(x_matrix.ndim)  # output: 2

2


In [ ]:
# reshape y to a matrix of size (3, 1)
y_matrix = y.reshape(3, 1)

# find the number of dimensions of y_matrix
print(y_matrix.ndim)  # output: 2

2


#Note that both x_matrix and y_matrix are 2-dimensional arrays/matrices after the reshaping operation.

# question 8:How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

Broadcasting allows mathematical operations on arrays of unequal shapes by treating them as if their contents have been replicated along appropriate dimensions [2]. In NumPy, broadcast-compatible arrays must have aligned dimensions with the same size or one dimension with a size of 1 [2].examples using 3*3 matrice

In [ ]:
# Create two matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Subtract B from A
C = A - B
print(C)

# Multiply A and B
D = A * B
print(D)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


#Note that the shapes of the matrices must be compatible for broadcasting to work. In this case, both matrices have the same shape, so broadcasting is not an issue. However, if the matrices had different shapes, we would need to use the broadcast_to function to reshape them appropriately,Additionally, if the shapes are incompatible, NumPy will raise a ValueError indicating that the operation cannot be performed.

#question 8:Add Markdown text, with a headline, that provides a very brief overview of the graphs (e.g., one sentence for each). 


LINE GRAPH: information is shown as a series of data points connected by straight line segments.

BAR GRAPH: is a form of graph in which data is represented by rectangular bars.

A scatter plot is a form of graph that shows values for two variables as a collection of points.


#part B

1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and 
          determine the number of solutions using the functions. 
	         1. 2x1+3x2-4x3=6,x1-4x2=8

             
	         2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [ ]:
import numpy as np

A = np.array([[2, 3, -4], [1, -4, 0]])
B = np.array([6, 8])

# Solve for x using matrix multiplication
x = np.linalg.solve(A, B)
print(x)

LinAlgError: Last 2 dimensions of the array must be square

2:3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [ ]:
A = np.array([[3, -4, 5], [-1, 2, -4]])
B = np.array([10, 8])

# Solve for y using matrix multiplication
y = np.linalg.solve(A, B)
print(y)

LinAlgError: Last 2 dimensions of the array must be square

#To determine the number of solutions, we can look at the rank of the coefficient matrix and the augmented matrix. If the rank of the coefficient matrix is equal to the rank of the augmented matrix, then there is a unique solution. If the rank of the coefficient matrix is less than the rank of the augmented matrix, then there are infinitely many solutions