## Part A

Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [14]:
#Create an array that starts from the integer 1, ends at 20, incremented by 3. using numpy
import numpy as np
Array1 = np.arange(1,20,3)
print(Array1)


[ 1  4  7 10 13 16 19]


Create a new array of shape 3 with random numbers between 0 and 1.

In [15]:
#Create a new array of shape 3 with random numbers between 0 and 1.
Array2 = np.random.rand(3)
print(Array2)

[0.79186736 0.54251308 0.49447488]


Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [16]:
#Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]]
Array3 = np.array([[10,20,45], [30,12,16], [42,17,56]])
#Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.
print(Array3[0:2])
print(Array3[1:3])

[[10 20 45]
 [30 12 16]]
[[30 12 16]
 [42 17 56]]


Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [17]:
#Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.
Array4 = np.array([[1,2],[3,4]])
Array5 = np.array([[5,6],[7,8]])
print(np.vstack((Array4,Array5)))
print(np.hstack((Array4,Array5)))
#split the arrays into smaller arrays.
print(np.split(Array4,2))
print(np.split(Array5,2))



[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[array([[1, 2]]), array([[3, 4]])]
[array([[5, 6]]), array([[7, 8]])]


Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
     
Demonstrate the case when it is not possible to.

In [18]:
#Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
     
      #Demonstrate the case when it is not possible to.
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])
print(np.dot(X,Y))


[[70 28]
 [70 30]
 [60 26]]


It is not possible to multiply these matrices because the number of columns in the first matrix is not equal to the number of rows in the second matrix

Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.

Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).


In [19]:
#Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])
print(x.shape)

#Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).
print(x.reshape(3,1))

(3,)
[[ 2]
 [-1]
 [-8]]


How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [20]:
# Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix. using broadcasting
matrixA = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrixB = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrixA-matrixB)
print(matrixA*matrixB)





[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


Broadcasting is used to create arrays with different shapes which can be used to arithmetic operations such as subtractions, multiplications and more.

## Part B

Solve the following two system of linear equations using matrices (find the values of x1 and x2) and 
      determine the number of solutions using the functions. 
      
         1.2x1+3x2-4x3=6,   x1-4x2=8
	
         2. 3y1-4y2+5y3=10,  -y1+2y2-4y3=8

In [27]:
arrayA= np.array([[2,3,-4],
                  [1,-4,0]])
arrayB = np.array([[6],
                   [8]])
resultX = np.linalg.solve(arrayA,arrayB)
x1 = resultX[0][0]
x2 = resultX[1][0]
print(x1,x2)

LinAlgError: Last 2 dimensions of the array must be square

To solve this question we need one more equation because it is necessary that all have same number of variables therefore there is error and have no solution.