# Henry Ezeanowi - 8900446
# LAB 1

# PART A

In [13]:
import numpy as np

2) Create an array that starts from the integer 1, ends at 20, incremented by 3

In [14]:
np.arange(1,20,3,dtype=int)

array([ 1,  4,  7, 10, 13, 16, 19])

3) Create a new array of shape 3 with random numbers between 0 and 1

In [15]:
np.random.rand(3)

array([0.15548375, 0.37081758, 0.70940123])

4) Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:

Slice the 2D array to get the first two rows

In [16]:
x=np.array([[10,20,45], [30,12,16], [42,17,56]])
#Slice the 2D array to get the first two rows
print(x[0:2])


[[10 20 45]
 [30 12 16]]


Slice the 2D array to get the last two rows

In [17]:
x=np.array([[10,20,45], [30,12,16], [42,17,56]])
#Slice the 2D array to get the last two rows
print(x[1:3])

[[30 12 16]
 [42 17 56]]


5) Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays

In [40]:

x1=np.array([[1,2],[3,4]])
x2=np.array([[6,7],[8,9]])

Stack the elements vertically

In [44]:
ver_stack = np.vstack([x1,x2])
print("The vertical stack \n", ver_stack)

The vertical stack 
 [[1 2]
 [3 4]
 [6 7]
 [8 9]]


Stack the elements horizontally


In [46]:
hor_stack = np.hstack([x1,x2])
print("The horizontal stack \n", hor_stack)

The horizontal stack 
 [[1 2 6 7]
 [3 4 8 9]]


Split the arrays into smaller arrays from vertical stack

In [50]:
print(np.split(x1,2))
print(np.split(x2,2))

[array([[1, 2]]), array([[3, 4]])]
[array([[6, 7]]), array([[8, 9]])]


Split the arrays into smaller arrays from horizontal stack

In [49]:
print(np.split(x1,2,axis=1))
print(np.split(x2,2,axis=1))

[array([[1],
       [3]]), array([[2],
       [4]])]
[array([[6],
       [8]]), array([[7],
       [9]])]


6) Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
     
    Demonstrate the case when it is not possible to

In [51]:
X=np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) 
Y=np.array([[4, 2], [6, 2], [4, 2]])
np.matmul(X,Y)

array([[70, 28],
       [70, 30],
       [60, 26]])

np.matmul(Y,X) is not possible, it gives an error since you cannot multiply a 3x2 matrix by a 3x3

In [20]:
np.matmul(Y,X)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

7) Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
     
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [37]:
x = np.array([2, -1, -8]) 
y = np.array([3, 1, -2])

Find the Shape, Number of dimensions of vector x

In [38]:
print('The shape of x is :',x.shape)
print('The dimension of x is :',x.ndim)

The shape of x is : (3,)
The dimension of x is : 1


Reshape the vector x to a matrix of size (3,1)

In [39]:
print("The reshaped matrix x is: \n", x.reshape((3, 1)))

The reshaped matrix x is: 
 [[ 2]
 [-1]
 [-8]]


Determine the number of dimensions after reshaping y to a matrix of (3,1)

In [ ]:
reshaped_y = y.reshape((3, 1))
print('The number of dimensions after reshaping y to a matrix of (3,1) is:', reshaped_y.ndim)

8) How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [55]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Subtraction from a scalar; subtracts 2 from each element of the matrix

In [56]:
print(x - 2)

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


Multiplication with a scalar; multiplys 2 to each element of the matrix

In [59]:
print(x * 2) 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Multiplication by element; multiplies the matrix by its element

In [34]:
print(x*x)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


# Part B1

We cannot solve the equation, because the shapes of the arrays are inconsistent

In [32]:
a = np.array([[2,3,-4],[1,-4]])
b = np.array([6,8])
x = np.linalg.solve(a, b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# Part B2

In [52]:
a = np.array([[3,-4,5],[-1,2,-4]])
b = np.array([10,8])
x = np.linalg.solve(a,b)

LinAlgError: Last 2 dimensions of the array must be square