**Lab 1 – Basic NumPy Operations**

1.Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [1]:
#import numpy package
import numpy as np

In [2]:
arr1 = np.arange(1,20,3)
arr1


array([ 1,  4,  7, 10, 13, 16, 19])

2.Create a new array of shape 3 with random numbers between 0 and 1.

In [3]:
arr2=np.random.rand(3)
arr2

array([0.62708271, 0.88523648, 0.61223287])

3.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56] and perform the following operations: 
     
       Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [4]:
arr3 = np.array([[10,20,45], [30,12,16], [42,17,56]])
arr3

# Slice the 2D array to get the first two rows
first_two_rows =arr3[0:2]
print(first_two_rows)

# slice the 2D array to get the last two rows.
last_two_rows =arr3[:0:-1]
print(last_two_rows)

[[10 20 45]
 [30 12 16]]
[[42 17 56]
 [30 12 16]]


4.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [5]:
arr4= np.array([[1,2],[3,4]])
arr5 =np.array([[5,6],[7,8]])

#stacking the elements horizontally
h_stack=np.hstack([arr4,arr5])
print(h_stack)

#stacking the elements vertically
v_stack=np.vstack([arr4,arr5])
print(v_stack)

#splitting the horizontal stack
split_hstack=np.array_split(h_stack,2)
print(split_hstack)

##splitting the vertical stack
split_vstack=np.array_split(v_stack,2)
print(split_vstack)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


5.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
     
      Demonstrate the case when it is not possible to.

In [6]:
#creating 2 matrices
X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) 
Y= ([[4, 2], [6, 2], [4, 2]])

#multiply x and y
np.matmul(X,Y)

array([[70, 28],
       [70, 30],
       [60, 26]])

The above code is multiplied by (x,y), however it cannot be multiplied by (y,x) as the y has 3x2 matrix and x has 3x3 matrix.
**so multiplying (y,x) is not possible.**

6.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
     
      Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [7]:
#creating 2 arrays
x = np.array([2, -1, -8]) 
y = np.array([3, 1, -2])

#printing the shape of x
print(x.shape)

#printing the dimension of x
print(x.ndim)

#reshaping x and y
print(x.reshape(3,1))
print(y.reshape(3,1).ndim)


(3,)
1
[[ 2]
 [-1]
 [-8]]
2


7.How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

Broadcasting describe how arrays with different shapes are treated during arithmetic operations, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [8]:
#creating a 3x3 matrix
arr6 = np.array([[ 0.0,  0.0,  0.0],
                 [10.0, 10.0, 10.0],
                 [20.0, 20.0, 20.0]])
arr7=np.array([1,2,3])# scalar


# subtraction
print("subtraction using broadcasting: \n",arr6-arr7)
# multiplication
print("multiplication using broadcasting : \n" ,arr6*arr7)


subtraction using broadcasting: 
 [[-1. -2. -3.]
 [ 9.  8.  7.]
 [19. 18. 17.]]
multiplication using broadcasting : 
 [[ 0.  0.  0.]
 [10. 20. 30.]
 [20. 40. 60.]]


**PART-B**

Solve the following two system of linear equations using matrices (find the values of x1 and x2) and 
      

determine the number of solutions using the functions.
1. 2x1+3x2-4x3=6, x1-4x2=8

In [10]:
a = np.array([[2,3,-4],[1,-4,0]])
b =  np.array([6,8])

#finding the shape
print(" shape of a matrix is: \n", a.shape)
print("shape of b matrix is: \n", b.shape)

#solving using linear algorithim ( which throws error)
print(np.linalg.solve(a,b))

 shape of a matrix is: 
 (2, 3)
shape of b matrix is: 
 (2,)


while finding the linalg it throws error

The error "Last 2 dimensions of the array must be square" occurs when using the np.linalg.solve function in NumPy. This error indicates that the input matrix used for solving a system of linear equations should be square, meaning it has an equal number of rows and columns.

In the given code snippet, the matrix X has dimensions 2x3, which means it is not a square matrix. To use np.linalg.solve, we need to provide a square matrix as the coefficient matrix.

To resolve this issue, we can check the dimensions of the matrix X and ensure that it is a square matrix. If it is not square, we might need to review the system of equations or adjust the dimensions of the matrix accordingly.

 2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [12]:
c = np.array([[3,-4,5],[-1,2,-4]])

# Defining the constants matrix for given set of equations
d = np.array([10,8])

#finding the shape
print("shape of c matrix is: \n", c.shape)
print("shape of d matrix is: \n", d.shape)


#solving using linear algorithim ( which throws error)
print(np.linalg.solve(c,d))

shape of c matrix is: 
 (2, 3)
shape of d matrix is: 
 (2,)


while finding the linalg it throws error

The error "Last 2 dimensions of the array must be square" occurs when using the np.linalg.solve function in NumPy. This error indicates that the input matrix used for solving a system of linear equations should be square, meaning it has an equal number of rows and columns.

In the given code snippet, the matrix X has dimensions 2x3, which means it is not a square matrix. To use np.linalg.solve, we need to provide a square matrix as the coefficient matrix.

To resolve this issue, we can check the dimensions of the matrix X and ensure that it is a square matrix. If it is not square, we might need to review the system of equations or adjust the dimensions of the matrix accordingly.