##  Hamir Ranavaya - 8802243
### Lab-1 Basic Numpy Operations.

# PART A

Q1. Create a Notebook to demonstrate NumPy Operations.

In [3]:
# Importing necessary packages
import numpy as np

Q2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [5]:
# Creating an array starting from 1 to 20 with the intervals of 3.
array = np.arange(1,20,3)
print(array)

[ 1  4  7 10 13 16 19]


Q3. Create a new array of shape 3 with random numbers between 0 and 1.

In [10]:
# Creating another array of shape 3 with random numbers (0 and 1).
array = np.random.rand(3)
print("array",array)

array [0.70714975 0.45726268 0.18736487]


Q4. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [16]:
# Creating a 2-D array
array = np.array([[10,20,45],[30,12,16],[42,17,56]])

#Slicing first two rows:
slf2r = array[0:2]
print(slf2r)

#Slicing last two rows:
sll2r = array[0:-1]
print(sll2r)

[[10 20 45]
 [30 12 16]]
[[10 20 45]
 [30 12 16]]


Q5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [24]:
array_1 = np.array([[2,4],[6,8]])
array_2 = np.array([[3,5],[7,9]])

#Stacking Vertically
stackverti = np.vstack([array_1,array_2])
print(stackverti)

#Stacking Horizontally
stackhori = np.hstack([array_1,array_2])
print(stackhori)

#spliting vertically
splverti = np.array_split(stackverti,2)
print(splverti)

#splitting horizontally
splhori = np.array_split(stackhori,2)
print(splhori)


[[2 4]
 [6 8]
 [3 5]
 [7 9]]
[[2 4 3 5]
 [6 8 7 9]]
[array([[2, 4],
       [6, 8]]), array([[3, 5],
       [7, 9]])]
[array([[2, 4, 3, 5]]), array([[6, 8, 7, 9]])]


Q6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?
Demonstrate the case when it is not possible to.

In [25]:
#creating 2 Matrices
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

#Multiplying both the Matrices
M = X @ Y
print(M)

[[70 28]
 [70 30]
 [60 26]]


###### Here Martics X has dimensions (3X3), where as Matrics Y has dimesions (3X2). SSince both the matrices has different dimensions, multiplication of matrices would not be possible.

Q7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [27]:
X = np.array([2, -1, -8])
Y = np.array([3, 1, -2])

#Finding the shape of X and Y
print('shape of X is', X.shape)
print('shape of Y is', Y.shape)

#Determining the number of Dimensions
print('Number of Dimensions of X are', X.ndim)
print('Number of Dimensions of Y are', Y.ndim)

#Reshaping X
print('reshaping X as', X.reshape(3,1))

#Reshaping Y to a matrix of (3,1)
print('reshaping Y to (3,1) matrix and it dimensions are', Y.reshape((3,1)).ndim)



shape of X is (3,)
shape of Y is (3,)
Number of Dimensions of X are 1
Number of Dimensions of Y are 1
reshaping X as [[ 2]
 [-1]
 [-8]]
reshaping Y to (3,1) matrix and it dimensions are 2


Q8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

Broadcasting helps arrays of various shapes and combine them together and it also adjust to the shape while managing operations.

In [32]:
X = np.array([[2,4,6],
              [3,5,7],
              [8,9,10]])
Y = np.array([[1,3,5],
              [2,4,6],
              [7,8,9]])

#Subtraction of both the arrays of 3x3 matrix
Sub = X - Y
print('Subtraction of matrices are')
print(Sub)

#Multiplication of both the arrays of 3x3 matric
Multi = X * Y
print('Multiplication of matrices are')
print(Multi)


Subtraction of matrices are
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Multiplication of matrices are
[[ 2 12 30]
 [ 6 20 42]
 [56 72 90]]


Q9. Add Markdown text, with a headline, that provides a very brief overview of the graphs (e.g., one sentence for each).
Feel free to add additional Markdown elements (description/additional comments).

### Scatterplot Graph
##### A Scatterplot graph represents the relationship between two different features. The graph provides information in dots(points).
 
### Histogram Plot
##### A Histogram plot is mostly used in order to generate a graph for vairous variables or features. One of the example of such a plot is frequency distribution.

### Line Graph
##### A line graph represents a line on a graph on the basis of the points given to the graph. It plots the graph using straigh lines.

### Piechart Graph
##### A pie graph is a circular graph which can show the data of various features in form of slices. 

# Part B


Q1. Solve the following two system of linear equations using matrices (find the values of x1 and x2) and
determine the number of solutions using the functions. 
1. 2x1+3x2-4x3=6, x1-4x2=8
2. 3y1-4y2+5y3=10, -y1+2y2-4y3=8

1. For 2x1+3x2-4x3=6, x1-4x2=8

##### Here the co-efficients of the above equations for x are x1, x2 and x3 and the co-effiecients of Y are y1 and y2. Inshort, The above equation represents [x1,x2,x3] and [y1,y2]. As mentioned earlier, in order to find a solution, we need atleast 3 variable of y in this condition. We have dimesnions [3x2] which is not possible to get a result. To determine a function is is mandatory to have equall shape such as [2x2] or [3x3].


If we place any random values of x1, x2 and x3 into the equation (say 2,3,4) respectively, we get:

2(2) + 3(3) -4(4) = 6

4 + 9 - 16 = 6

-3 = 6

WHICH DOESNOT SATISFY THE EQUATION. Hence by taking any numbers it would not be possible to solve this equation

In [39]:
#From both the equations, we can determine x1,x2 and x3 as (2,3,-4) and (1,-4,0)
A = np.array([[2,3,],[1,-4,]])
#From the above equation, we can say that the vector is (6,8)
B = np.array([6,8])

print('The solution for the equation is', np.linalg.solve(A, B))

The solution for the equation is [ 4.36363636 -0.90909091]


We were able to solve A and B if I neglect any one co-efficient from x coordinate. Since the dimensions are now [2x2] we were able to solve the equation.

2. 3y1-4y2+5y3=10, -y1+2y2-4y3=8

As mentioned in the case above,we need same dimensions of matrix. If we add a third equation we would be able to solve this equation.

Taking one more equation into consideration.


3y1-2y2 = 12

In [40]:
A = np.array([[3, -4, 5], [-1, 2, 4],[3, -2, 0]])
B = np.array([10,8, 12])
print('The solution of the equation is',np.linalg.solve(A,B))

The solution of the equation is [7.09090909 4.63636364 1.45454545]
