# Lab #1
#### Billy Parmenter - 7526387
## Part A

In [87]:
import numpy as np

Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [88]:
arr = np.arange(1, 20, 3)
arr

array([ 1,  4,  7, 10, 13, 16, 19])

Create a new array of shape 3 with random numbers between 0 and 1.

In [89]:
arr = np.random.rand(3)
arr

array([0.3777329 , 0.98244909, 0.12061864])

Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:  
- Slice the 2D array to get the first two rows.
- Slice the 2D array to get the last two rows.

In [90]:
arr = np.array([[10,20,45], [30,12,16], [42,17,56]])
arr[:2]

array([[10, 20, 45],
       [30, 12, 16]])

In [91]:
arr[-2:]

array([[30, 12, 16],
       [42, 17, 56]])

Create two 2x2 arrays and demonstrate how you can:
- stack the elements 
    - vertically
    - horizontally
- split the arrays into smaller arrays.

In [92]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[11,12],[13,14]])
np.stack((arr1, arr2), axis=0)

array([[[ 1,  2],
        [ 3,  4]],

       [[11, 12],
        [13, 14]]])

In [93]:
np.stack((arr1, arr2), axis=1)

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]]])

Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]])
- Is it possible to multiply these matrices?
- Demonstrate the case when it is not possible to.

In [94]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

In [95]:
np.dot(X,Y)

array([[70, 28],
       [70, 30],
       [60, 26]])

In [96]:
Y = np.reshape(Y,[2, 3])
np.dot(X,Y)


ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2])
- For vector X find:
    - Shape
    - Number of dimensions 
- Reshape the vector x to a matrix of size (3,1) 
- determine the number of dimensions after reshaping y to a matrix of (3,1).

In [97]:
X = np.array([2, -1, -8])
Y = np.array([3, 1, -2])
X.shape

(3,)

In [98]:
X.ndim

1

In [99]:
X = np.reshape(X,[3,1])
Y = np.reshape(Y,[3,1])
Y.shape

(3, 1)

In [100]:
Y.ndim

2

How does broadcasting work? 
- Demonstrate the following on a 3 x 3 matrix:
    - subtraction
    - multiplication

In [101]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
mat - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [103]:
mat * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## Part B

Solve the following two system of linear equations using matrices 
- Find the values for the variables
- Determine the number of solutions

<br>System 1:
> $2x1+3x2-4x3=6$<br>$x1-4x2=8$

In [104]:
Ax = np.array([[2,3,-4],[1,-4]])
Bx = np.array([6,8])
Xx = np.linalg.solve(Ax, Bx)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

System 2:
> $3y1-4y2+5y3=10$<br>$-y1+2y2-4y3=8$

In [105]:
Ay = np.array([[3,-4,5],[-1,2,-4]])
By = np.array([10,8])
Xy = np.linalg.solve(Ay, By)

LinAlgError: Last 2 dimensions of the array must be square

There is no solutions for either system.
- The first system has too many variables ($x3$) to have a solution.
- The second system does not have enough functions to solve for 3 variables.