# Lifei Wang 
## 8855277
## CSCN8000-Lab1

### Part A:

1. Create a Notebook to demonstrate NumPy Operations.

In [1]:
import numpy as np

2. Create an array that starts from the integer 1, ends at 20, incremented by 3.


In [2]:
arr1 = np.arange(1, 20, 3, dtype=int)
arr1

array([ 1,  4,  7, 10, 13, 16, 19])

3. Create a new array of shape 3 with random numbers between 0 and 1.


In [3]:
np.random.seed(20)
arr2 = np.random.rand(3)
arr2

array([0.5881308 , 0.89771373, 0.89153073])

4. Create a 2D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
         
    Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [4]:
arr3 = np.array([[10,20,45], [30,12,16], [42,17,56]])
print('2D array: \n', arr3)
arr3_first_2rows = arr3[:2, :]
print('First two rows: \n', arr3_first_2rows)
arr3_last_2rows = arr3[1:, :]
print('Last two rows: \n', arr3_last_2rows)


2D array: 
 [[10 20 45]
 [30 12 16]
 [42 17 56]]
First two rows: 
 [[10 20 45]
 [30 12 16]]
Last two rows: 
 [[30 12 16]
 [42 17 56]]


5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [5]:
# create 2D arrays
arr4 = np.random.randint(10, size=(2,2))
print('The first 2D array: \n', arr4)
arr5 = np.random.randint(10, size=(2,2))
print('The second 2D array: \n', arr5)

# stack vertically
stack_vertical =  np.vstack((arr4, arr5))
print('Stack vertically: \n', stack_vertical)

# stack horizontally
stack_horizontal = np.hstack((arr4, arr5))
print('Stack horizontally: \n', stack_horizontal)

# split vertically
split_vertical = np.vsplit(stack_vertical, 2)
print('Split vertically: \n', split_vertical)

# split horizontally
split_horizontal = np.hsplit(stack_horizontal, 2)
print('Split horizontally: \n', split_horizontal)
np.split

The first 2D array: 
 [[9 4]
 [6 7]]
The second 2D array: 
 [[2 0]
 [6 8]]
Stack vertically: 
 [[9 4]
 [6 7]
 [2 0]
 [6 8]]
Stack horizontally: 
 [[9 4 2 0]
 [6 7 6 8]]
Split vertically: 
 [array([[9, 4],
       [6, 7]]), array([[2, 0],
       [6, 8]])]
Split horizontally: 
 [array([[9, 4],
       [6, 7]]), array([[2, 0],
       [6, 8]])]


<function numpy.split(ary, indices_or_sections, axis=0)>

6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
         
    Demonstrate the case when it is not possible to.

In [12]:
x = np.matrix([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
print('matrix x:\n', x)
y = np.matrix([[4, 2], [6, 2], [4, 2]])
print('matrix y:\n',y)
print('multiply x by y:\n', x*y)

# when x and y have different dimensions, it is not possible to multiply them
y_2 = np.matrix([[4, 2], [6, 2]])
# in this case, x can not be multiplied by y_2

matrix x:
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
matrix y:
 [[4 2]
 [6 2]
 [4 2]]
multiply x by y:
 [[70 28]
 [70 30]
 [60 26]]


7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.


    Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [23]:
x = np.array([2, -1, -8])
print('x: \n', x)
print('shape of x: ', x.shape)
print('number of dimensions: ', x.ndim)

# reshape x to matrix of size (3,1)
reshape_x = np.reshape(x, (3,1))
print('\nreshape_x: \n', reshape_x)
print('number of dimensions of reshape_x: ', reshape_x.ndim)

y = np.array([3, 1, -2])
print('\ny: \n', y)
print('shape of y: ', y.shape)
print('number of dimensions of y: ', y.ndim)
reshape_y = np.reshape(y, (3,1))
print('\nreshape_y: \n', reshape_y)
print('number of dimensions of reshape_y: ', reshape_y.ndim)



x: 
 [ 2 -1 -8]
shape of x:  (3,)
number of dimensions:  1

reshape_x: 
 [[ 2]
 [-1]
 [-8]]
number of dimensions of reshape_x:  2

y: 
 [ 3  1 -2]
shape of y:  (3,)
number of dimensions of y:  1

reshape_y: 
 [[ 3]
 [ 1]
 [-2]]
number of dimensions of reshape_y:  2


8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [28]:
# create a 3x3 matrix
arr6 = np.random.randint(10, size=(3,3))
print('3x3 matrix: \n', arr6)

# broadcast by subtraction
arr6_sub = arr6 - 10
print('\nmatrix subtraction: \n', arr6_sub)

# broadcast by multiplication
arr6_mul = arr6 * 5
print('\nmatrix multiplication: \n', arr6_mul)

3x3 matrix: 
 [[4 8 6]
 [2 3 1]
 [5 2 1]]

matrix subtraction: 
 [[-6 -2 -4]
 [-8 -7 -9]
 [-5 -8 -9]]

matrix multiplication: 
 [[20 40 30]
 [10 15  5]
 [25 10  5]]


9. Add Markdown text, with a headline, that provides a very brief overview of the graphs (e.g., one sentence for each). 
         
    Feel free to add additional Markdown elements (description/additional comments)

### Graphs
* **scatter plot**
    * represent relationship between two variables using individual dots and markers
* **Histogram graph**
    * graphical representation of distribution of dataset by dividing into bins
    * display the frequency of data within each bin
* **Bar chart**
    * represent frequency of categorical data with rectangular bars
* **Line graph**
    * display data points connected with straight lines
    * show trends, change over time
* **Pie chart**
    * represent proportion or percentage of dataset in a circular graph
* **Area graph**
    * represent cumulative total or distribution of data
* **Heatmap**
    * represent data using colored matrix
    * visualize intensity or concentration
* **Box plot**
    * display summary of data distribution
    * include min, 1st quartile, 2nd quartile(median), 3rd quartile, max, and outliers
    * provide insights of central tendency, spread and skewness of data

10. Push the notebook to your lab-submission fork, and create a PR

### Part B:

1. Solve the following two system of linear equations using matrices (find the values of x1 and x2) and 
    determine the number of solutions using the functions. 

	$2x1+3x2-4x3=6$

	$x1-4x2=8$

	<br>
		
	$3y1-4y2+5y3=10$

	$-y1+2y2-4y3=8$

In [47]:
# solve system 1 of linear equations
a = np.array([[2, 3, -4], [1, -4, 0]])
b = np.array([6, 8])
# result_1 = np.linalg.solve(a, b)
print('Result of 1st system of linear equations: ', result_1)

# it can not be solved since it is not squared matrix and will report linalg error

Result of 1st system of linear equations:  (array([ 1.6692112, -1.5826972, -1.8524173]), array([], dtype=float64), 2, array([5.8874361 , 3.36720896]))


In [48]:
# solve system 2 of linear equations
c = np.array([[3, -4, 5], [-1, 2, -4]])
d = np.array([10, 8])
# result_2 = np.linalg.solve(c, d)
print('Result of 2nd system of linear equations: ', result_2)

# it can not be solved since it is not squared matrix and will report linalg error

Result of 2nd system of linear equations:  (array([ 7.46067416, -4.62921348, -6.17977528]), array([], dtype=float64), 2, array([8.35006167, 1.12980976]))


In [56]:
# create a function to determine how many solutions
def num_solutions(arr1, arr2):
    # get augmented matrix
    augmented_matrix = np.column_stack((arr1, arr2))
    print('augmented matrix:\n', augmented_matrix)

    # Number of how many variables
    num_vars = arr1.shape[1]
    print('number of variables:', num_vars)

    # get rank of arr1 and augment matrix
    rank_arr1 = np.linalg.matrix_rank(arr1)
    print('rank of arr1:', rank_arr1)

    rank_augmented_matrix = np.linalg.matrix_rank(augmented_matrix)
    print('rank of augmented matrix:', rank_augmented_matrix)

    if rank_arr1 == rank_augmented_matrix == num_vars:
        solutions = 'Unique Solution'
    elif rank_arr1 == rank_augmented_matrix < num_vars:
        solutions = 'Infinite Solutions'
    else:
        solutions = 'No solution'

    print('number of solutions:', solutions, '\n')

num_solutions(a, b)
num_solutions(c, d)

augmented matrix:
 [[ 2  3 -4  6]
 [ 1 -4  0  8]]
number of variables: 3
rank of arr1: 2
rank of augmented matrix: 2
number of solutions: Infinite Solutions 

augmented matrix:
 [[ 3 -4  5 10]
 [-1  2 -4  8]]
number of variables: 3
rank of arr1: 2
rank of augmented matrix: 2
number of solutions: Infinite Solutions 



2. Publish the notebook as an HTML using GitHub Pages
	
	In the PR description (created above) - add the direct link to the HTML.