Practical Lab-1  Mohammed Abuzar Younus - 8903244
Basic Numpy Operations
Part-A


1.Create a Notebook to demonstrate NumPy Operations.

In [2]:
import numpy as np 


2.Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [3]:
array_with_steps = np.arange(1, 20, 3) # (start,stop, step)
print("array_with_steps :", array_with_steps)

array_with_steps : [ 1  4  7 10 13 16 19]


3.Create a new array of shape 3 with random numbers between 0 and 1

In [4]:
array_from_0_to_1 = np.random.rand(3)
print("array_from_0_to_1 :",array_from_0_to_1)

array_from_0_to_1 : [0.27350078 0.6444539  0.52827136]


4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows,
slice the 2D array to get the last two rows.

In [5]:
array = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print(array)
print("The dimensions of the array_2d:", array.ndim)

# Slice the 2D array to get the first two rows

first_two_rows = array[:2, :]
print("First two rows:", first_two_rows)

# Slice the 2D array to get the last two rows

last_two_rows = array[1:, :]
print("Last two rows:", last_two_rows)

[[10 20 45]
 [30 12 16]
 [42 17 56]]
The dimensions of the array_2d: 2
First two rows: [[10 20 45]
 [30 12 16]]
Last two rows: [[30 12 16]
 [42 17 56]]


5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [6]:
# Create the two 2x2 array

arr1 = np.array([[11,12],[13,14]])
arr2 = np.array([[15,16],[17,18]])

# Stack the arrays horizontally
h_stack = np.hstack((arr1, arr2))
print("The horizontally stacked array is : \n", h_stack)
# Stack the arrays vertically
v_stack = np.vstack((arr1, arr2))
print("The vertically stacked array is : \n", v_stack)

# Splitting the 2 x 4 horizontally stacked array into 4 smaller arrays along the columns

split_h_array = np.array_split(h_stack, indices_or_sections = 4, axis = 1) # Similar to np.vsplit(h_array, 4)
print("The splitted arrays generated from h_array splitting are: \n", split_h_array)

# Splitting the 4 x 2 horizontally stacked array into 4 smaller arrays along the rows

split_v_array = np.array_split(v_stack, indices_or_sections=4, axis = 0) # Similar to np.hsplit(v_array, 4)
print("The splitted arrays generated from v_array splitting are: \n", split_v_array)






The horizontally stacked array is : 
 [[11 12 15 16]
 [13 14 17 18]]
The vertically stacked array is : 
 [[11 12]
 [13 14]
 [15 16]
 [17 18]]
The splitted arrays generated from h_array splitting are: 
 [array([[11],
       [13]]), array([[12],
       [14]]), array([[15],
       [17]]), array([[16],
       [18]])]
The splitted arrays generated from v_array splitting are: 
 [array([[11, 12]]), array([[13, 14]]), array([[15, 16]]), array([[17, 18]])]


6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? Demonstrate the case when it is not possible to.

In [7]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])
print("The shape of X matrix is: \n", X.shape)
print("The shape of Y matrix is: \n", Y.shape)

# Multiply X and Y matrices

# As the number of columns in X matrix is equal to the number of rows in Y matrix, we can multiply X with Y

Z = np.matmul(X, Y) # we can achieve the same with Z = X @ Y  or Z = X.dot(Y)

print("The product of X and Y is a 3 X 2 matrix: \n", Z)
print("Yes it is possible and shown in above example.")

The shape of X matrix is: 
 (3, 3)
The shape of Y matrix is: 
 (3, 2)
The product of X and Y is a 3 X 2 matrix: 
 [[70 28]
 [70 30]
 [60 26]]
Yes it is possible and shown in above example.


7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.


     

In [8]:
X = np.array([2, -1, -8])
Y = np.array([3, 1, -2])


print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)


print("Number of dimensions X:", X.ndim)
print("Number of dimensions Y:", Y.ndim)

Shape of X: (3,)
Shape of Y: (3,)
Number of dimensions X: 1
Number of dimensions Y: 1


Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1)

In [9]:
X_reshaped = X.reshape(3, 1)
Y_reshaped = Y.reshape(3, 1)
print(X_reshaped)
print(Y_reshaped)
print("Number of dimensions after reshaping X:", X_reshaped.ndim)
print("Number of dimensions after reshaping Y:", Y_reshaped.ndim)

[[ 2]
 [-1]
 [-8]]
[[ 3]
 [ 1]
 [-2]]
Number of dimensions after reshaping X: 2
Number of dimensions after reshaping Y: 2


8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.
Broadcasting is a feature of NumPy which used for arithmetic operations on arrays with different matrix sizes. When any arithmetic operation is applied on a matrix, numpy vectorizes the array operation by looping through the matrix element by element. This process is called as broadcasting.

In [10]:


# Create a 3x3 matrix
mat1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
mat2 = 2
# Perform subtraction operation
subtraction_result = mat1 - mat2

# Perform multiplication operation
multiplication_result = mat1 * 3

# Print the original matrix
print("Original Matrix:")
print(mat1)

# Print the result of subtraction
print("\nSubtraction Result:")
print(subtraction_result)

# Print the result of multiplication
print("\nMultiplication Result:")
print(multiplication_result)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtraction Result:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Multiplication Result:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


Part B

 1.Solve the following two system of linear equations using matrices (find the values of x1 and x2) and 

  determine the number of solutions using the functions. 
         
  1.2x1+3x2-4x3=6,x1-4x2=8

2x1 + 3x2 - 4x3 = 6
x1 - 4x2 = 8
We can represent this system in matrix form as AX = B, where A is the coefficient matrix, X is the variable matrix, and B is the constant matrix.

Coefficient Matrix (A):

|  2   3  -4 |
|  1  -4   0 |

Variable Matrix (X):
| x1 |
| x2 |
| x3 |

|  6 |
|  8 |


To solve for X, we can use the equation X = A^(-1) * B, where A^(-1) is the inverse of matrix A.

In [11]:
# Coefficient Matrix A
A = np.array([[2, 3, -4],
              [1, -4, 0]])

# Constant Matrix B
B = np.array([6, 8])

# Solve for X


print("Solution:")
print("x1 =", X[0])
print("x2 =", X[1])

Solution:
x1 = 2
x2 = -1


X = np.linalg.solve(A, B)

When attempting to carry out a matrix operation that needs the array's final two dimensions to be square, the LinAlgError occurs. In other words, the matrix's number of rows and columns must match.

When using the np.linalg.solve() function to solve a system of linear equations in the provided code, an error is raised. The number of rows and columns must match for the matrix to be a square matrix, as required by the solution() method.

The matrix X in the offered example is 2x3, meaning it has 2 rows and 3 columns. The matrix is not square since the number of rows and columns is not equal, hence the solution() function cannot be used.

You must make sure that the matrix used to represent the system of linear equations is square in order to correct this issue. This implies that a square matrix should be produced by having an equal number of equations and unknowns.

 2. 3y1-4y2+5y3=10,-y1+2y2-4y3=8

In [12]:
A = np.array([[3, -4, 5],
              [-1, 2, -4]])

# Constant Matrix C
C = np.array([10, 8])

# Solve for Y


print("\nSolution:")
print("y1 =", Y[0])
print("y2 =", Y[1])
print("y3 =", Y[2])


Solution:
y1 = 3
y2 = 1
y3 = -2


Y = np.linalg.solve(A, C)

When attempting to carry out a matrix operation that needs the array's final two dimensions to be square, the LinAlgError occurs. In other words, the matrix's number of rows and columns must match.

When using the np.linalg.solve() function to solve a system of linear equations in the provided code, an error is raised. The number of rows and columns must match for the matrix to be a square matrix, as required by the solution() method.

The matrix X in the offered example is 2x3, meaning it has 2 rows and 3 columns. The matrix is not square since the number of rows and columns is not equal, hence the solution() function cannot be used.

You must make sure that the matrix used to represent the system of linear equations is square in order to correct this issue. This implies that a square matrix should be produced by having an equal number of equations and unknowns.