## Lab 1
Part A

1. Create a Notebook to demonstrate NumPy Operations.

In [2]:
import numpy as np

2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [3]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

3. Create a new array of shape 3 with random numbers between 0 and 1.

In [4]:
np.random.rand(3)

array([0.64589289, 0.9552894 , 0.69020625])

4. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
    *   Slice the 2D array to get the first two rows
    *   slice the 2D array to get the last two rows.

In [7]:
A = np.array([[10,20,45], [30,12,16], [42,17,56]])
print('Slice the 2D array to get the first two rows')
print(A[:2])
print('slice the 2D array to get the last two rows.')
print(A[-2:])


Slice the 2D array to get the first two rows
[[10 20 45]
 [30 12 16]]
slice the 2D array to get the last two rows.
[[30 12 16]
 [42 17 56]]


5. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [26]:
A = np.zeros((2, 2),dtype=int)
B = np.ones((2, 2),dtype=int)
print("Horizontal stack : \n", np.hstack([A,B]))
print("Vertical stack : \n", np.vstack([A,B]))
print("The splitted arrays from horizontal stack", np.array_split(np.hstack([A,B]), indices_or_sections = 2, axis = 0))
print("The splitted arrays from vertical stack", np.array_split(np.vstack([A,B]), indices_or_sections = 2, axis = 0))

Horizontal stack : 
 [[0 0 1 1]
 [0 0 1 1]]
Vertical stack : 
 [[0 0]
 [0 0]
 [1 1]
 [1 1]]
The splitted arrays from horizontal stack [array([[0, 0, 1, 1]]), array([[0, 0, 1, 1]])]
The splitted arrays from vertical stack [array([[0, 0],
       [0, 0]]), array([[1, 1],
       [1, 1]])]


6. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices?

In [28]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])
print(np.dot(X,Y))
print(np.dot(Y,X))

[[70 28]
 [70 30]
 [60 26]]


ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

7. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).



In [31]:

X = np.array([2, -1, -8])
Y = np.array([3, 1, -2])
print("Shape")
print(X.shape)
print("Dimension")
print(X.ndim)
X = np.reshape(X,[3,1])
Y = np.reshape(Y,[3,1])
print("Reshaped Y dimension")
print(Y.ndim)

Shape
(3,)
Dimension
1
Reshaped Y dimension
2


8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.
Broadcasting help to perform operations on arrays with different shapes.



In [47]:
A = np.random.randint(10,size=(3,3))
print(A)
print(A-1)
print(A*3)

[[7 3 0]
 [8 4 1]
 [3 8 2]]
[[ 6  2 -1]
 [ 7  3  0]
 [ 2  7  1]]
[[21  9  0]
 [24 12  3]
 [ 9 24  6]]


Part B
1. Solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions. $2x_1$ + $3x_2$ - $4x_3$ = 6, $x_1$ - $4x_2$ = 8. $3y_1$ - $4y_2$ + $5y_3$ = 10 , $-y_1$ + $2y_2$ - $4y_3$ = 8

In [48]:
A1 = np.array([[2,3,-4],[1,-4]])
B1 = np.array([6,8])
X1 = np.linalg.solve(A1, B1)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [49]:
A2 = np.array([[3,-4,5],[-1,2,-4]])
B2 = np.array([10,8])
X2 = np.linalg.solve(A2, B2)

LinAlgError: Last 2 dimensions of the array must be square

For matrix determinant or matrix inversion, the matrix has to be square matrices, which defines the number of solutions, hence the system of equations are unsolvable.