In [1]:
import numpy as np

2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [2]:
array = np.arange(1, 20, 3)
print( array)

[ 1  4  7 10 13 16 19]


 3. Create a new array of shape 3 with random numbers between 0 and 1.


In [3]:
random_array = np.random.rand(3)
print( random_array)

[0.29709763 0.27565156 0.41857622]


4. Create a 2D array and perform slicing operations.


In [4]:
array_2d = np.array([[10,20,45], [30,12,16], [42,17,56]])
# Slice to get first two rows
print("First two rows: ", array_2d[:2])
# Slice to get last two rows
print("Last two rows: ", array_2d[-2:])

First two rows:  [[10 20 45]
 [30 12 16]]
Last two rows:  [[30 12 16]
 [42 17 56]]


5. Demonstrate stacking and splitting of 2x2 arrays.


In [5]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
# Stack vertically
print("Vertical Stack: ", np.vstack((arr1, arr2)))
# Stack horizontally
print("Horizontal Stack: ", np.hstack((arr1, arr2)))
# Split the arrays
print("Split arrays: ", np.split(arr1, 2))

Vertical Stack:  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:  [[1 2 5 6]
 [3 4 7 8]]
Split arrays:  [array([[1, 2]]), array([[3, 4]])]


6. Matrix multiplication.


In [6]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4 ,2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

result = np.matmul(X, Y)
print("Matrix Multiplication: ", result)

Matrix Multiplication:  [[70 28]
 [70 30]
 [60 26]]


In [9]:
result = np.matmul(Y, X)
## not possible because of size incompatible

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

7. Shape, dimensions, and reshaping of arrays.

In [10]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print("Shape of x: ", x.shape)
print("Number of dimensions of x: ", x.ndim)

x_reshaped = x.reshape(3,1)
print("Shape of x after reshaping: ", x_reshaped.shape)
print("Number of dimensions of x after reshaping: ", x_reshaped.ndim)

Shape of x:  (3,)
Number of dimensions of x:  1
Shape of x after reshaping:  (3, 1)
Number of dimensions of x after reshaping:  2


8. Broadcasting with subtraction, multiplication.


In [11]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print("Subtraction after broadcasting: ", matrix - 1)
print("Multiplication after broadcasting: ", matrix * 2)


Subtraction after broadcasting:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
Multiplication after broadcasting:  [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
