# LAB 1 - SUDHAN SHRESTHA [8889436]

#### 1.Create a Notebook to demonstrate NumPy Operations.

In [1]:
# importing necessary packages
import numpy as np

### PART A:
#### 2. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [5]:
array1 = np.arange(1,20,3)
array1

array([ 1,  4,  7, 10, 13, 16, 19])

#### 3.Create a new array of shape 3 with random numbers between 0 and 1.

In [9]:
array2 = np.random.rand(3)
print("The array:", array2)
print ("Shape of the array:", array2.shape)

The array: [0.72391922 0.24475003 0.03810084]
Shape of the array: (3,)


#### 4.Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations: 
     
#### Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [14]:
# Creating the 2D array.
array2D = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("The 2D array:\n",array2D)
# Printing out the dimentions
print("\n The dimentions of the array:",array2D.ndim)

The 2D array:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]

 The dimentions of the array: 2


In [17]:
# Slicing the 2D array to get first two rows
print("The first two rows:\n", array2D[:2])

# Slicing the 2D array to get the last two rows
print("The last two rows:\n", array2D[1:])

The first two rows:
 [[10 20 45]
 [30 12 16]]
The last two rows:
 [[30 12 16]
 [42 17 56]]


#### 5.Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [38]:
# Creating a 2x2 arrays 
arrayStack1 = np.array([[1, 2], [3, 4]])
arrayStack2 = np.array([[5, 6], [7, 8]])

# Vertically stacking the arrays:
verticalStack = np.vstack((arrayStack1, arrayStack2))
print("Vertically Stacked Array: \n", verticalStack)

# Horizontally stacking the arrays:
horizontalStack = np.hstack((arrayStack1, arrayStack2))
print("\nHorizontally Stacked Array: \n", horizontalStack)

# Splitting the arrays into smaller arrays
smallArray1 = np.array_split(verticalStack, 2)
smallArray2 = np.array_split(horizontalStack, 4,1)
print("Splititing the vertical array: \n",smallArray1)
print("Splititing the horizontal array: \n",smallArray2)

Vertically Stacked Array: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally Stacked Array: 
 [[1 2 5 6]
 [3 4 7 8]]
Splititing the vertical array: 
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
Splititing the horizontal array: 
 [array([[1],
       [3]]), array([[2],
       [4]]), array([[5],
       [7]]), array([[6],
       [8]])]


#### 6.Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]), Is it possible to multiply these matrices? 
#### Demonstrate the case when it is not possible to.

In [44]:
# Creating the two matrices 
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Shape of these matruces 
print("The shape of X: ",X.shape)
print("The shape of Y: ",Y.shape)
# Multiplying these matrices

ans = np.matmul( X, Y)
print("\nProduct of X and Y:\n", ans)
print("\nThe shape of the product: ",ans.shape)

The shape of X:  (3, 3)
The shape of Y:  (3, 2)

Product of X and Y:
 [[70 28]
 [70 30]
 [60 26]]

The shape of the product:  (3, 2)


Yes, the multiplication of theses two matrices is possible because the number of column of first matrix X which is 3, is equals to the number of row of the second matrix Y which is 3 as well.

But, in case of mulitplication of Y and X it would not be possile as the number of column of Y which is 2 is not equal to the number of row of X which is 3. Let us demonstrace the case below :

In [45]:
error_ans = np.matmul(Y,X) # error due to mismatch dimensions

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

#### 7.Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]), Find the Shape, Number of dimensions of vector x.
     
#### Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [50]:
# Creating the array
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Shape of the vector x
print("Shape of vector x: ", x.shape)
# Dimensions of vector x
print("Dimension of vector x: ", x.ndim)

# Reshaping x to a matrix of size (3,1)
x = x.reshape(3,1)
# Reshaping y to a matrix of (3,1)
y = y.reshape(3,1)

# Printing out the shape of x and y after reshaping
print("\nShape of x after reshaping: ", x.shape)
print("Shape of y after reshaping: ", y.shape)

# Printing out the dimensions of both x and y after reshaping
print("\nDimension of x after reshaping: ", x.ndim)
print("Dimension of y after reshaping: ", y.ndim)

Shape of vector x:  (3,)
Dimension of vector x:  1

Shape of x after reshaping:  (3, 1)
Shape of y after reshaping:  (3, 1)

Dimension of x after reshaping:  2
Dimension of y after reshaping:  2


#### 8. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

The term `broadcasting` refers to how Numpy treats array with different shapes during arithmetic operations. `Boradcasting` works by automatically making changes to the dimensions of two arrays with mismatch shapes to match each other, so that various arthemetic operations could be perfomed between them.

Source - [Numpy Docs](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [57]:
# Demonstrating arithematic operations with a 3 x 3 matrix

# Demonstrating broadcastin with array and a scalar value
array3_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
c = 10

# Subtraction
sub = array3_3 - c
print("Subtraction:\narray3_3 - c = \n", sub)

# Multiplication
multi = array3_3 * c
print("\nMultiplication:\narray3_3 * c = \n", multi)


Subtraction:
array3_3 - c = 
 [[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]

Multiplication:
array3_3 * c = 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
